/*
 * This file is generated by jOOQ.
 */
package net.cowpi.client.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import net.cowpi.client.jooq.tables.CowpiUser;
import net.cowpi.client.jooq.tables.Prekey;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -2067858509;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>cowpi_user</code>.
     */
    public final CowpiUser COWPI_USER = net.cowpi.client.jooq.tables.CowpiUser.COWPI_USER;

    /**
     * The table <code>prekey</code>.
     */
    public final Prekey PREKEY = net.cowpi.client.jooq.tables.Prekey.PREKEY;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            CowpiUser.COWPI_USER,
            Prekey.PREKEY);
    }
}
