/*
 * This file is generated by jOOQ.
 */
package net.cowpi.client.jooq;


import javax.annotation.Generated;

import net.cowpi.client.jooq.tables.CowpiUser;
import net.cowpi.client.jooq.tables.Prekey;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SQLITE_AUTOINDEX_COWPI_USER_1 = Indexes0.SQLITE_AUTOINDEX_COWPI_USER_1;
    public static final Index SQLITE_AUTOINDEX_PREKEY_1 = Indexes0.SQLITE_AUTOINDEX_PREKEY_1;
    public static final Index SQLITE_AUTOINDEX_PREKEY_2 = Indexes0.SQLITE_AUTOINDEX_PREKEY_2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SQLITE_AUTOINDEX_COWPI_USER_1 = Internal.createIndex("sqlite_autoindex_cowpi_user_1", CowpiUser.COWPI_USER, new OrderField[] { CowpiUser.COWPI_USER.USERNAME }, true);
        public static Index SQLITE_AUTOINDEX_PREKEY_1 = Internal.createIndex("sqlite_autoindex_prekey_1", Prekey.PREKEY, new OrderField[] { Prekey.PREKEY.PREKEY_ }, true);
        public static Index SQLITE_AUTOINDEX_PREKEY_2 = Internal.createIndex("sqlite_autoindex_prekey_2", Prekey.PREKEY, new OrderField[] { Prekey.PREKEY.USER_ID, Prekey.PREKEY.KEY_ID }, true);
    }
}
