/*
 * This file is generated by jOOQ.
 */
package net.cowpi.client.jooq;


import javax.annotation.Generated;

import net.cowpi.client.jooq.tables.CowpiUser;
import net.cowpi.client.jooq.tables.Prekey;
import net.cowpi.client.jooq.tables.records.CowpiUserRecord;
import net.cowpi.client.jooq.tables.records.PrekeyRecord;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CowpiUserRecord> PK_COWPI_USER = UniqueKeys0.PK_COWPI_USER;
    public static final UniqueKey<CowpiUserRecord> SQLITE_AUTOINDEX_COWPI_USER_1 = UniqueKeys0.SQLITE_AUTOINDEX_COWPI_USER_1;
    public static final UniqueKey<PrekeyRecord> PK_PREKEY = UniqueKeys0.PK_PREKEY;
    public static final UniqueKey<PrekeyRecord> SQLITE_AUTOINDEX_PREKEY_2 = UniqueKeys0.SQLITE_AUTOINDEX_PREKEY_2;
    public static final UniqueKey<PrekeyRecord> SQLITE_AUTOINDEX_PREKEY_1 = UniqueKeys0.SQLITE_AUTOINDEX_PREKEY_1;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CowpiUserRecord> PK_COWPI_USER = Internal.createUniqueKey(CowpiUser.COWPI_USER, "pk_cowpi_user", CowpiUser.COWPI_USER.ID);
        public static final UniqueKey<CowpiUserRecord> SQLITE_AUTOINDEX_COWPI_USER_1 = Internal.createUniqueKey(CowpiUser.COWPI_USER, "sqlite_autoindex_cowpi_user_1", CowpiUser.COWPI_USER.USERNAME);
        public static final UniqueKey<PrekeyRecord> PK_PREKEY = Internal.createUniqueKey(Prekey.PREKEY, "pk_prekey", Prekey.PREKEY.ID);
        public static final UniqueKey<PrekeyRecord> SQLITE_AUTOINDEX_PREKEY_2 = Internal.createUniqueKey(Prekey.PREKEY, "sqlite_autoindex_prekey_2", Prekey.PREKEY.USER_ID, Prekey.PREKEY.KEY_ID);
        public static final UniqueKey<PrekeyRecord> SQLITE_AUTOINDEX_PREKEY_1 = Internal.createUniqueKey(Prekey.PREKEY, "sqlite_autoindex_prekey_1", Prekey.PREKEY.PREKEY_);
    }
}
