/*
 * This file is generated by jOOQ.
 */
package net.cowpi.oes.jooq.tables.records;


import javax.annotation.Generated;

import net.cowpi.oes.jooq.tables.Conversation;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConversationRecord extends UpdatableRecordImpl<ConversationRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 673367273;

    /**
     * Setter for <code>conversation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>conversation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>conversation.conversation_id</code>.
     */
    public void setConversationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>conversation.conversation_id</code>.
     */
    public Long getConversationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>conversation.next_index</code>.
     */
    public void setNextIndex(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>conversation.next_index</code>.
     */
    public Long getNextIndex() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Conversation.CONVERSATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Conversation.CONVERSATION.CONVERSATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Conversation.CONVERSATION.NEXT_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getConversationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getNextIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getConversationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getNextIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationRecord value2(Long value) {
        setConversationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationRecord value3(Long value) {
        setNextIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConversationRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConversationRecord
     */
    public ConversationRecord() {
        super(Conversation.CONVERSATION);
    }

    /**
     * Create a detached, initialised ConversationRecord
     */
    public ConversationRecord(Long id, Long conversationId, Long nextIndex) {
        super(Conversation.CONVERSATION);

        set(0, id);
        set(1, conversationId);
        set(2, nextIndex);
    }
}
