// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Oes.proto

package net.cowpi.protobuf;

public final class OesProto {
  private OesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OesContainerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OesContainer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
     */
    boolean hasOesUploadPrekeys();
    /**
     * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
     */
    net.cowpi.protobuf.OesProto.OesUploadPrekeys getOesUploadPrekeys();
    /**
     * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
     */
    net.cowpi.protobuf.OesProto.OesUploadPrekeysOrBuilder getOesUploadPrekeysOrBuilder();

    /**
     * <code>.CowpiMessage cowpi_message = 2;</code>
     */
    boolean hasCowpiMessage();
    /**
     * <code>.CowpiMessage cowpi_message = 2;</code>
     */
    net.cowpi.protobuf.MessageProto.CowpiMessage getCowpiMessage();
    /**
     * <code>.CowpiMessage cowpi_message = 2;</code>
     */
    net.cowpi.protobuf.MessageProto.CowpiMessageOrBuilder getCowpiMessageOrBuilder();

    public net.cowpi.protobuf.OesProto.OesContainer.InnerCase getInnerCase();
  }
  /**
   * Protobuf type {@code OesContainer}
   */
  public  static final class OesContainer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OesContainer)
      OesContainerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OesContainer.newBuilder() to construct.
    private OesContainer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OesContainer() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OesContainer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              net.cowpi.protobuf.OesProto.OesUploadPrekeys.Builder subBuilder = null;
              if (innerCase_ == 1) {
                subBuilder = ((net.cowpi.protobuf.OesProto.OesUploadPrekeys) inner_).toBuilder();
              }
              inner_ =
                  input.readMessage(net.cowpi.protobuf.OesProto.OesUploadPrekeys.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((net.cowpi.protobuf.OesProto.OesUploadPrekeys) inner_);
                inner_ = subBuilder.buildPartial();
              }
              innerCase_ = 1;
              break;
            }
            case 18: {
              net.cowpi.protobuf.MessageProto.CowpiMessage.Builder subBuilder = null;
              if (innerCase_ == 2) {
                subBuilder = ((net.cowpi.protobuf.MessageProto.CowpiMessage) inner_).toBuilder();
              }
              inner_ =
                  input.readMessage(net.cowpi.protobuf.MessageProto.CowpiMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((net.cowpi.protobuf.MessageProto.CowpiMessage) inner_);
                inner_ = subBuilder.buildPartial();
              }
              innerCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.cowpi.protobuf.OesProto.internal_static_OesContainer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.cowpi.protobuf.OesProto.internal_static_OesContainer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.cowpi.protobuf.OesProto.OesContainer.class, net.cowpi.protobuf.OesProto.OesContainer.Builder.class);
    }

    private int innerCase_ = 0;
    private java.lang.Object inner_;
    public enum InnerCase
        implements com.google.protobuf.Internal.EnumLite {
      OES_UPLOAD_PREKEYS(1),
      COWPI_MESSAGE(2),
      INNER_NOT_SET(0);
      private final int value;
      private InnerCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static InnerCase valueOf(int value) {
        return forNumber(value);
      }

      public static InnerCase forNumber(int value) {
        switch (value) {
          case 1: return OES_UPLOAD_PREKEYS;
          case 2: return COWPI_MESSAGE;
          case 0: return INNER_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public InnerCase
    getInnerCase() {
      return InnerCase.forNumber(
          innerCase_);
    }

    public static final int OES_UPLOAD_PREKEYS_FIELD_NUMBER = 1;
    /**
     * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
     */
    public boolean hasOesUploadPrekeys() {
      return innerCase_ == 1;
    }
    /**
     * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
     */
    public net.cowpi.protobuf.OesProto.OesUploadPrekeys getOesUploadPrekeys() {
      if (innerCase_ == 1) {
         return (net.cowpi.protobuf.OesProto.OesUploadPrekeys) inner_;
      }
      return net.cowpi.protobuf.OesProto.OesUploadPrekeys.getDefaultInstance();
    }
    /**
     * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
     */
    public net.cowpi.protobuf.OesProto.OesUploadPrekeysOrBuilder getOesUploadPrekeysOrBuilder() {
      if (innerCase_ == 1) {
         return (net.cowpi.protobuf.OesProto.OesUploadPrekeys) inner_;
      }
      return net.cowpi.protobuf.OesProto.OesUploadPrekeys.getDefaultInstance();
    }

    public static final int COWPI_MESSAGE_FIELD_NUMBER = 2;
    /**
     * <code>.CowpiMessage cowpi_message = 2;</code>
     */
    public boolean hasCowpiMessage() {
      return innerCase_ == 2;
    }
    /**
     * <code>.CowpiMessage cowpi_message = 2;</code>
     */
    public net.cowpi.protobuf.MessageProto.CowpiMessage getCowpiMessage() {
      if (innerCase_ == 2) {
         return (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_;
      }
      return net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance();
    }
    /**
     * <code>.CowpiMessage cowpi_message = 2;</code>
     */
    public net.cowpi.protobuf.MessageProto.CowpiMessageOrBuilder getCowpiMessageOrBuilder() {
      if (innerCase_ == 2) {
         return (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_;
      }
      return net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (innerCase_ == 1) {
        output.writeMessage(1, (net.cowpi.protobuf.OesProto.OesUploadPrekeys) inner_);
      }
      if (innerCase_ == 2) {
        output.writeMessage(2, (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (innerCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (net.cowpi.protobuf.OesProto.OesUploadPrekeys) inner_);
      }
      if (innerCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.cowpi.protobuf.OesProto.OesContainer)) {
        return super.equals(obj);
      }
      net.cowpi.protobuf.OesProto.OesContainer other = (net.cowpi.protobuf.OesProto.OesContainer) obj;

      if (!getInnerCase().equals(other.getInnerCase())) return false;
      switch (innerCase_) {
        case 1:
          if (!getOesUploadPrekeys()
              .equals(other.getOesUploadPrekeys())) return false;
          break;
        case 2:
          if (!getCowpiMessage()
              .equals(other.getCowpiMessage())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (innerCase_) {
        case 1:
          hash = (37 * hash) + OES_UPLOAD_PREKEYS_FIELD_NUMBER;
          hash = (53 * hash) + getOesUploadPrekeys().hashCode();
          break;
        case 2:
          hash = (37 * hash) + COWPI_MESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getCowpiMessage().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.cowpi.protobuf.OesProto.OesContainer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cowpi.protobuf.OesProto.OesContainer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesContainer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cowpi.protobuf.OesProto.OesContainer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesContainer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cowpi.protobuf.OesProto.OesContainer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesContainer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cowpi.protobuf.OesProto.OesContainer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesContainer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.cowpi.protobuf.OesProto.OesContainer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesContainer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cowpi.protobuf.OesProto.OesContainer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.cowpi.protobuf.OesProto.OesContainer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OesContainer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OesContainer)
        net.cowpi.protobuf.OesProto.OesContainerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.cowpi.protobuf.OesProto.internal_static_OesContainer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.cowpi.protobuf.OesProto.internal_static_OesContainer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.cowpi.protobuf.OesProto.OesContainer.class, net.cowpi.protobuf.OesProto.OesContainer.Builder.class);
      }

      // Construct using net.cowpi.protobuf.OesProto.OesContainer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        innerCase_ = 0;
        inner_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.cowpi.protobuf.OesProto.internal_static_OesContainer_descriptor;
      }

      @java.lang.Override
      public net.cowpi.protobuf.OesProto.OesContainer getDefaultInstanceForType() {
        return net.cowpi.protobuf.OesProto.OesContainer.getDefaultInstance();
      }

      @java.lang.Override
      public net.cowpi.protobuf.OesProto.OesContainer build() {
        net.cowpi.protobuf.OesProto.OesContainer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.cowpi.protobuf.OesProto.OesContainer buildPartial() {
        net.cowpi.protobuf.OesProto.OesContainer result = new net.cowpi.protobuf.OesProto.OesContainer(this);
        if (innerCase_ == 1) {
          if (oesUploadPrekeysBuilder_ == null) {
            result.inner_ = inner_;
          } else {
            result.inner_ = oesUploadPrekeysBuilder_.build();
          }
        }
        if (innerCase_ == 2) {
          if (cowpiMessageBuilder_ == null) {
            result.inner_ = inner_;
          } else {
            result.inner_ = cowpiMessageBuilder_.build();
          }
        }
        result.innerCase_ = innerCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.cowpi.protobuf.OesProto.OesContainer) {
          return mergeFrom((net.cowpi.protobuf.OesProto.OesContainer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.cowpi.protobuf.OesProto.OesContainer other) {
        if (other == net.cowpi.protobuf.OesProto.OesContainer.getDefaultInstance()) return this;
        switch (other.getInnerCase()) {
          case OES_UPLOAD_PREKEYS: {
            mergeOesUploadPrekeys(other.getOesUploadPrekeys());
            break;
          }
          case COWPI_MESSAGE: {
            mergeCowpiMessage(other.getCowpiMessage());
            break;
          }
          case INNER_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.cowpi.protobuf.OesProto.OesContainer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.cowpi.protobuf.OesProto.OesContainer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int innerCase_ = 0;
      private java.lang.Object inner_;
      public InnerCase
          getInnerCase() {
        return InnerCase.forNumber(
            innerCase_);
      }

      public Builder clearInner() {
        innerCase_ = 0;
        inner_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          net.cowpi.protobuf.OesProto.OesUploadPrekeys, net.cowpi.protobuf.OesProto.OesUploadPrekeys.Builder, net.cowpi.protobuf.OesProto.OesUploadPrekeysOrBuilder> oesUploadPrekeysBuilder_;
      /**
       * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
       */
      public boolean hasOesUploadPrekeys() {
        return innerCase_ == 1;
      }
      /**
       * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
       */
      public net.cowpi.protobuf.OesProto.OesUploadPrekeys getOesUploadPrekeys() {
        if (oesUploadPrekeysBuilder_ == null) {
          if (innerCase_ == 1) {
            return (net.cowpi.protobuf.OesProto.OesUploadPrekeys) inner_;
          }
          return net.cowpi.protobuf.OesProto.OesUploadPrekeys.getDefaultInstance();
        } else {
          if (innerCase_ == 1) {
            return oesUploadPrekeysBuilder_.getMessage();
          }
          return net.cowpi.protobuf.OesProto.OesUploadPrekeys.getDefaultInstance();
        }
      }
      /**
       * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
       */
      public Builder setOesUploadPrekeys(net.cowpi.protobuf.OesProto.OesUploadPrekeys value) {
        if (oesUploadPrekeysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          inner_ = value;
          onChanged();
        } else {
          oesUploadPrekeysBuilder_.setMessage(value);
        }
        innerCase_ = 1;
        return this;
      }
      /**
       * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
       */
      public Builder setOesUploadPrekeys(
          net.cowpi.protobuf.OesProto.OesUploadPrekeys.Builder builderForValue) {
        if (oesUploadPrekeysBuilder_ == null) {
          inner_ = builderForValue.build();
          onChanged();
        } else {
          oesUploadPrekeysBuilder_.setMessage(builderForValue.build());
        }
        innerCase_ = 1;
        return this;
      }
      /**
       * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
       */
      public Builder mergeOesUploadPrekeys(net.cowpi.protobuf.OesProto.OesUploadPrekeys value) {
        if (oesUploadPrekeysBuilder_ == null) {
          if (innerCase_ == 1 &&
              inner_ != net.cowpi.protobuf.OesProto.OesUploadPrekeys.getDefaultInstance()) {
            inner_ = net.cowpi.protobuf.OesProto.OesUploadPrekeys.newBuilder((net.cowpi.protobuf.OesProto.OesUploadPrekeys) inner_)
                .mergeFrom(value).buildPartial();
          } else {
            inner_ = value;
          }
          onChanged();
        } else {
          if (innerCase_ == 1) {
            oesUploadPrekeysBuilder_.mergeFrom(value);
          }
          oesUploadPrekeysBuilder_.setMessage(value);
        }
        innerCase_ = 1;
        return this;
      }
      /**
       * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
       */
      public Builder clearOesUploadPrekeys() {
        if (oesUploadPrekeysBuilder_ == null) {
          if (innerCase_ == 1) {
            innerCase_ = 0;
            inner_ = null;
            onChanged();
          }
        } else {
          if (innerCase_ == 1) {
            innerCase_ = 0;
            inner_ = null;
          }
          oesUploadPrekeysBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
       */
      public net.cowpi.protobuf.OesProto.OesUploadPrekeys.Builder getOesUploadPrekeysBuilder() {
        return getOesUploadPrekeysFieldBuilder().getBuilder();
      }
      /**
       * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
       */
      public net.cowpi.protobuf.OesProto.OesUploadPrekeysOrBuilder getOesUploadPrekeysOrBuilder() {
        if ((innerCase_ == 1) && (oesUploadPrekeysBuilder_ != null)) {
          return oesUploadPrekeysBuilder_.getMessageOrBuilder();
        } else {
          if (innerCase_ == 1) {
            return (net.cowpi.protobuf.OesProto.OesUploadPrekeys) inner_;
          }
          return net.cowpi.protobuf.OesProto.OesUploadPrekeys.getDefaultInstance();
        }
      }
      /**
       * <code>.OesUploadPrekeys oes_upload_prekeys = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.cowpi.protobuf.OesProto.OesUploadPrekeys, net.cowpi.protobuf.OesProto.OesUploadPrekeys.Builder, net.cowpi.protobuf.OesProto.OesUploadPrekeysOrBuilder> 
          getOesUploadPrekeysFieldBuilder() {
        if (oesUploadPrekeysBuilder_ == null) {
          if (!(innerCase_ == 1)) {
            inner_ = net.cowpi.protobuf.OesProto.OesUploadPrekeys.getDefaultInstance();
          }
          oesUploadPrekeysBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.cowpi.protobuf.OesProto.OesUploadPrekeys, net.cowpi.protobuf.OesProto.OesUploadPrekeys.Builder, net.cowpi.protobuf.OesProto.OesUploadPrekeysOrBuilder>(
                  (net.cowpi.protobuf.OesProto.OesUploadPrekeys) inner_,
                  getParentForChildren(),
                  isClean());
          inner_ = null;
        }
        innerCase_ = 1;
        onChanged();;
        return oesUploadPrekeysBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          net.cowpi.protobuf.MessageProto.CowpiMessage, net.cowpi.protobuf.MessageProto.CowpiMessage.Builder, net.cowpi.protobuf.MessageProto.CowpiMessageOrBuilder> cowpiMessageBuilder_;
      /**
       * <code>.CowpiMessage cowpi_message = 2;</code>
       */
      public boolean hasCowpiMessage() {
        return innerCase_ == 2;
      }
      /**
       * <code>.CowpiMessage cowpi_message = 2;</code>
       */
      public net.cowpi.protobuf.MessageProto.CowpiMessage getCowpiMessage() {
        if (cowpiMessageBuilder_ == null) {
          if (innerCase_ == 2) {
            return (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_;
          }
          return net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance();
        } else {
          if (innerCase_ == 2) {
            return cowpiMessageBuilder_.getMessage();
          }
          return net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.CowpiMessage cowpi_message = 2;</code>
       */
      public Builder setCowpiMessage(net.cowpi.protobuf.MessageProto.CowpiMessage value) {
        if (cowpiMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          inner_ = value;
          onChanged();
        } else {
          cowpiMessageBuilder_.setMessage(value);
        }
        innerCase_ = 2;
        return this;
      }
      /**
       * <code>.CowpiMessage cowpi_message = 2;</code>
       */
      public Builder setCowpiMessage(
          net.cowpi.protobuf.MessageProto.CowpiMessage.Builder builderForValue) {
        if (cowpiMessageBuilder_ == null) {
          inner_ = builderForValue.build();
          onChanged();
        } else {
          cowpiMessageBuilder_.setMessage(builderForValue.build());
        }
        innerCase_ = 2;
        return this;
      }
      /**
       * <code>.CowpiMessage cowpi_message = 2;</code>
       */
      public Builder mergeCowpiMessage(net.cowpi.protobuf.MessageProto.CowpiMessage value) {
        if (cowpiMessageBuilder_ == null) {
          if (innerCase_ == 2 &&
              inner_ != net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance()) {
            inner_ = net.cowpi.protobuf.MessageProto.CowpiMessage.newBuilder((net.cowpi.protobuf.MessageProto.CowpiMessage) inner_)
                .mergeFrom(value).buildPartial();
          } else {
            inner_ = value;
          }
          onChanged();
        } else {
          if (innerCase_ == 2) {
            cowpiMessageBuilder_.mergeFrom(value);
          }
          cowpiMessageBuilder_.setMessage(value);
        }
        innerCase_ = 2;
        return this;
      }
      /**
       * <code>.CowpiMessage cowpi_message = 2;</code>
       */
      public Builder clearCowpiMessage() {
        if (cowpiMessageBuilder_ == null) {
          if (innerCase_ == 2) {
            innerCase_ = 0;
            inner_ = null;
            onChanged();
          }
        } else {
          if (innerCase_ == 2) {
            innerCase_ = 0;
            inner_ = null;
          }
          cowpiMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.CowpiMessage cowpi_message = 2;</code>
       */
      public net.cowpi.protobuf.MessageProto.CowpiMessage.Builder getCowpiMessageBuilder() {
        return getCowpiMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.CowpiMessage cowpi_message = 2;</code>
       */
      public net.cowpi.protobuf.MessageProto.CowpiMessageOrBuilder getCowpiMessageOrBuilder() {
        if ((innerCase_ == 2) && (cowpiMessageBuilder_ != null)) {
          return cowpiMessageBuilder_.getMessageOrBuilder();
        } else {
          if (innerCase_ == 2) {
            return (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_;
          }
          return net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.CowpiMessage cowpi_message = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.cowpi.protobuf.MessageProto.CowpiMessage, net.cowpi.protobuf.MessageProto.CowpiMessage.Builder, net.cowpi.protobuf.MessageProto.CowpiMessageOrBuilder> 
          getCowpiMessageFieldBuilder() {
        if (cowpiMessageBuilder_ == null) {
          if (!(innerCase_ == 2)) {
            inner_ = net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance();
          }
          cowpiMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.cowpi.protobuf.MessageProto.CowpiMessage, net.cowpi.protobuf.MessageProto.CowpiMessage.Builder, net.cowpi.protobuf.MessageProto.CowpiMessageOrBuilder>(
                  (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_,
                  getParentForChildren(),
                  isClean());
          inner_ = null;
        }
        innerCase_ = 2;
        onChanged();;
        return cowpiMessageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OesContainer)
    }

    // @@protoc_insertion_point(class_scope:OesContainer)
    private static final net.cowpi.protobuf.OesProto.OesContainer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.cowpi.protobuf.OesProto.OesContainer();
    }

    public static net.cowpi.protobuf.OesProto.OesContainer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OesContainer>
        PARSER = new com.google.protobuf.AbstractParser<OesContainer>() {
      @java.lang.Override
      public OesContainer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OesContainer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OesContainer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OesContainer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.cowpi.protobuf.OesProto.OesContainer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OesUploadPrekeysOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OesUploadPrekeys)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 prekeyCount = 1;</code>
     */
    int getPrekeyCount();

    /**
     * <code>repeated .OesPreKey oes_prekey = 2;</code>
     */
    java.util.List<net.cowpi.protobuf.OesProto.OesPreKey> 
        getOesPrekeyList();
    /**
     * <code>repeated .OesPreKey oes_prekey = 2;</code>
     */
    net.cowpi.protobuf.OesProto.OesPreKey getOesPrekey(int index);
    /**
     * <code>repeated .OesPreKey oes_prekey = 2;</code>
     */
    int getOesPrekeyCount();
    /**
     * <code>repeated .OesPreKey oes_prekey = 2;</code>
     */
    java.util.List<? extends net.cowpi.protobuf.OesProto.OesPreKeyOrBuilder> 
        getOesPrekeyOrBuilderList();
    /**
     * <code>repeated .OesPreKey oes_prekey = 2;</code>
     */
    net.cowpi.protobuf.OesProto.OesPreKeyOrBuilder getOesPrekeyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code OesUploadPrekeys}
   */
  public  static final class OesUploadPrekeys extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OesUploadPrekeys)
      OesUploadPrekeysOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OesUploadPrekeys.newBuilder() to construct.
    private OesUploadPrekeys(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OesUploadPrekeys() {
      oesPrekey_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OesUploadPrekeys(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              prekeyCount_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                oesPrekey_ = new java.util.ArrayList<net.cowpi.protobuf.OesProto.OesPreKey>();
                mutable_bitField0_ |= 0x00000002;
              }
              oesPrekey_.add(
                  input.readMessage(net.cowpi.protobuf.OesProto.OesPreKey.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          oesPrekey_ = java.util.Collections.unmodifiableList(oesPrekey_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.cowpi.protobuf.OesProto.internal_static_OesUploadPrekeys_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.cowpi.protobuf.OesProto.internal_static_OesUploadPrekeys_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.cowpi.protobuf.OesProto.OesUploadPrekeys.class, net.cowpi.protobuf.OesProto.OesUploadPrekeys.Builder.class);
    }

    private int bitField0_;
    public static final int PREKEYCOUNT_FIELD_NUMBER = 1;
    private int prekeyCount_;
    /**
     * <code>int32 prekeyCount = 1;</code>
     */
    public int getPrekeyCount() {
      return prekeyCount_;
    }

    public static final int OES_PREKEY_FIELD_NUMBER = 2;
    private java.util.List<net.cowpi.protobuf.OesProto.OesPreKey> oesPrekey_;
    /**
     * <code>repeated .OesPreKey oes_prekey = 2;</code>
     */
    public java.util.List<net.cowpi.protobuf.OesProto.OesPreKey> getOesPrekeyList() {
      return oesPrekey_;
    }
    /**
     * <code>repeated .OesPreKey oes_prekey = 2;</code>
     */
    public java.util.List<? extends net.cowpi.protobuf.OesProto.OesPreKeyOrBuilder> 
        getOesPrekeyOrBuilderList() {
      return oesPrekey_;
    }
    /**
     * <code>repeated .OesPreKey oes_prekey = 2;</code>
     */
    public int getOesPrekeyCount() {
      return oesPrekey_.size();
    }
    /**
     * <code>repeated .OesPreKey oes_prekey = 2;</code>
     */
    public net.cowpi.protobuf.OesProto.OesPreKey getOesPrekey(int index) {
      return oesPrekey_.get(index);
    }
    /**
     * <code>repeated .OesPreKey oes_prekey = 2;</code>
     */
    public net.cowpi.protobuf.OesProto.OesPreKeyOrBuilder getOesPrekeyOrBuilder(
        int index) {
      return oesPrekey_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (prekeyCount_ != 0) {
        output.writeInt32(1, prekeyCount_);
      }
      for (int i = 0; i < oesPrekey_.size(); i++) {
        output.writeMessage(2, oesPrekey_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (prekeyCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, prekeyCount_);
      }
      for (int i = 0; i < oesPrekey_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, oesPrekey_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.cowpi.protobuf.OesProto.OesUploadPrekeys)) {
        return super.equals(obj);
      }
      net.cowpi.protobuf.OesProto.OesUploadPrekeys other = (net.cowpi.protobuf.OesProto.OesUploadPrekeys) obj;

      if (getPrekeyCount()
          != other.getPrekeyCount()) return false;
      if (!getOesPrekeyList()
          .equals(other.getOesPrekeyList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PREKEYCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getPrekeyCount();
      if (getOesPrekeyCount() > 0) {
        hash = (37 * hash) + OES_PREKEY_FIELD_NUMBER;
        hash = (53 * hash) + getOesPrekeyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.cowpi.protobuf.OesProto.OesUploadPrekeys prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OesUploadPrekeys}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OesUploadPrekeys)
        net.cowpi.protobuf.OesProto.OesUploadPrekeysOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.cowpi.protobuf.OesProto.internal_static_OesUploadPrekeys_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.cowpi.protobuf.OesProto.internal_static_OesUploadPrekeys_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.cowpi.protobuf.OesProto.OesUploadPrekeys.class, net.cowpi.protobuf.OesProto.OesUploadPrekeys.Builder.class);
      }

      // Construct using net.cowpi.protobuf.OesProto.OesUploadPrekeys.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOesPrekeyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        prekeyCount_ = 0;

        if (oesPrekeyBuilder_ == null) {
          oesPrekey_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          oesPrekeyBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.cowpi.protobuf.OesProto.internal_static_OesUploadPrekeys_descriptor;
      }

      @java.lang.Override
      public net.cowpi.protobuf.OesProto.OesUploadPrekeys getDefaultInstanceForType() {
        return net.cowpi.protobuf.OesProto.OesUploadPrekeys.getDefaultInstance();
      }

      @java.lang.Override
      public net.cowpi.protobuf.OesProto.OesUploadPrekeys build() {
        net.cowpi.protobuf.OesProto.OesUploadPrekeys result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.cowpi.protobuf.OesProto.OesUploadPrekeys buildPartial() {
        net.cowpi.protobuf.OesProto.OesUploadPrekeys result = new net.cowpi.protobuf.OesProto.OesUploadPrekeys(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.prekeyCount_ = prekeyCount_;
        if (oesPrekeyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            oesPrekey_ = java.util.Collections.unmodifiableList(oesPrekey_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.oesPrekey_ = oesPrekey_;
        } else {
          result.oesPrekey_ = oesPrekeyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.cowpi.protobuf.OesProto.OesUploadPrekeys) {
          return mergeFrom((net.cowpi.protobuf.OesProto.OesUploadPrekeys)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.cowpi.protobuf.OesProto.OesUploadPrekeys other) {
        if (other == net.cowpi.protobuf.OesProto.OesUploadPrekeys.getDefaultInstance()) return this;
        if (other.getPrekeyCount() != 0) {
          setPrekeyCount(other.getPrekeyCount());
        }
        if (oesPrekeyBuilder_ == null) {
          if (!other.oesPrekey_.isEmpty()) {
            if (oesPrekey_.isEmpty()) {
              oesPrekey_ = other.oesPrekey_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureOesPrekeyIsMutable();
              oesPrekey_.addAll(other.oesPrekey_);
            }
            onChanged();
          }
        } else {
          if (!other.oesPrekey_.isEmpty()) {
            if (oesPrekeyBuilder_.isEmpty()) {
              oesPrekeyBuilder_.dispose();
              oesPrekeyBuilder_ = null;
              oesPrekey_ = other.oesPrekey_;
              bitField0_ = (bitField0_ & ~0x00000002);
              oesPrekeyBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOesPrekeyFieldBuilder() : null;
            } else {
              oesPrekeyBuilder_.addAllMessages(other.oesPrekey_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.cowpi.protobuf.OesProto.OesUploadPrekeys parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.cowpi.protobuf.OesProto.OesUploadPrekeys) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int prekeyCount_ ;
      /**
       * <code>int32 prekeyCount = 1;</code>
       */
      public int getPrekeyCount() {
        return prekeyCount_;
      }
      /**
       * <code>int32 prekeyCount = 1;</code>
       */
      public Builder setPrekeyCount(int value) {
        
        prekeyCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 prekeyCount = 1;</code>
       */
      public Builder clearPrekeyCount() {
        
        prekeyCount_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<net.cowpi.protobuf.OesProto.OesPreKey> oesPrekey_ =
        java.util.Collections.emptyList();
      private void ensureOesPrekeyIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          oesPrekey_ = new java.util.ArrayList<net.cowpi.protobuf.OesProto.OesPreKey>(oesPrekey_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.cowpi.protobuf.OesProto.OesPreKey, net.cowpi.protobuf.OesProto.OesPreKey.Builder, net.cowpi.protobuf.OesProto.OesPreKeyOrBuilder> oesPrekeyBuilder_;

      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public java.util.List<net.cowpi.protobuf.OesProto.OesPreKey> getOesPrekeyList() {
        if (oesPrekeyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(oesPrekey_);
        } else {
          return oesPrekeyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public int getOesPrekeyCount() {
        if (oesPrekeyBuilder_ == null) {
          return oesPrekey_.size();
        } else {
          return oesPrekeyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public net.cowpi.protobuf.OesProto.OesPreKey getOesPrekey(int index) {
        if (oesPrekeyBuilder_ == null) {
          return oesPrekey_.get(index);
        } else {
          return oesPrekeyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public Builder setOesPrekey(
          int index, net.cowpi.protobuf.OesProto.OesPreKey value) {
        if (oesPrekeyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOesPrekeyIsMutable();
          oesPrekey_.set(index, value);
          onChanged();
        } else {
          oesPrekeyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public Builder setOesPrekey(
          int index, net.cowpi.protobuf.OesProto.OesPreKey.Builder builderForValue) {
        if (oesPrekeyBuilder_ == null) {
          ensureOesPrekeyIsMutable();
          oesPrekey_.set(index, builderForValue.build());
          onChanged();
        } else {
          oesPrekeyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public Builder addOesPrekey(net.cowpi.protobuf.OesProto.OesPreKey value) {
        if (oesPrekeyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOesPrekeyIsMutable();
          oesPrekey_.add(value);
          onChanged();
        } else {
          oesPrekeyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public Builder addOesPrekey(
          int index, net.cowpi.protobuf.OesProto.OesPreKey value) {
        if (oesPrekeyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOesPrekeyIsMutable();
          oesPrekey_.add(index, value);
          onChanged();
        } else {
          oesPrekeyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public Builder addOesPrekey(
          net.cowpi.protobuf.OesProto.OesPreKey.Builder builderForValue) {
        if (oesPrekeyBuilder_ == null) {
          ensureOesPrekeyIsMutable();
          oesPrekey_.add(builderForValue.build());
          onChanged();
        } else {
          oesPrekeyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public Builder addOesPrekey(
          int index, net.cowpi.protobuf.OesProto.OesPreKey.Builder builderForValue) {
        if (oesPrekeyBuilder_ == null) {
          ensureOesPrekeyIsMutable();
          oesPrekey_.add(index, builderForValue.build());
          onChanged();
        } else {
          oesPrekeyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public Builder addAllOesPrekey(
          java.lang.Iterable<? extends net.cowpi.protobuf.OesProto.OesPreKey> values) {
        if (oesPrekeyBuilder_ == null) {
          ensureOesPrekeyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, oesPrekey_);
          onChanged();
        } else {
          oesPrekeyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public Builder clearOesPrekey() {
        if (oesPrekeyBuilder_ == null) {
          oesPrekey_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          oesPrekeyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public Builder removeOesPrekey(int index) {
        if (oesPrekeyBuilder_ == null) {
          ensureOesPrekeyIsMutable();
          oesPrekey_.remove(index);
          onChanged();
        } else {
          oesPrekeyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public net.cowpi.protobuf.OesProto.OesPreKey.Builder getOesPrekeyBuilder(
          int index) {
        return getOesPrekeyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public net.cowpi.protobuf.OesProto.OesPreKeyOrBuilder getOesPrekeyOrBuilder(
          int index) {
        if (oesPrekeyBuilder_ == null) {
          return oesPrekey_.get(index);  } else {
          return oesPrekeyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public java.util.List<? extends net.cowpi.protobuf.OesProto.OesPreKeyOrBuilder> 
           getOesPrekeyOrBuilderList() {
        if (oesPrekeyBuilder_ != null) {
          return oesPrekeyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(oesPrekey_);
        }
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public net.cowpi.protobuf.OesProto.OesPreKey.Builder addOesPrekeyBuilder() {
        return getOesPrekeyFieldBuilder().addBuilder(
            net.cowpi.protobuf.OesProto.OesPreKey.getDefaultInstance());
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public net.cowpi.protobuf.OesProto.OesPreKey.Builder addOesPrekeyBuilder(
          int index) {
        return getOesPrekeyFieldBuilder().addBuilder(
            index, net.cowpi.protobuf.OesProto.OesPreKey.getDefaultInstance());
      }
      /**
       * <code>repeated .OesPreKey oes_prekey = 2;</code>
       */
      public java.util.List<net.cowpi.protobuf.OesProto.OesPreKey.Builder> 
           getOesPrekeyBuilderList() {
        return getOesPrekeyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.cowpi.protobuf.OesProto.OesPreKey, net.cowpi.protobuf.OesProto.OesPreKey.Builder, net.cowpi.protobuf.OesProto.OesPreKeyOrBuilder> 
          getOesPrekeyFieldBuilder() {
        if (oesPrekeyBuilder_ == null) {
          oesPrekeyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.cowpi.protobuf.OesProto.OesPreKey, net.cowpi.protobuf.OesProto.OesPreKey.Builder, net.cowpi.protobuf.OesProto.OesPreKeyOrBuilder>(
                  oesPrekey_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          oesPrekey_ = null;
        }
        return oesPrekeyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OesUploadPrekeys)
    }

    // @@protoc_insertion_point(class_scope:OesUploadPrekeys)
    private static final net.cowpi.protobuf.OesProto.OesUploadPrekeys DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.cowpi.protobuf.OesProto.OesUploadPrekeys();
    }

    public static net.cowpi.protobuf.OesProto.OesUploadPrekeys getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OesUploadPrekeys>
        PARSER = new com.google.protobuf.AbstractParser<OesUploadPrekeys>() {
      @java.lang.Override
      public OesUploadPrekeys parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OesUploadPrekeys(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OesUploadPrekeys> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OesUploadPrekeys> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.cowpi.protobuf.OesProto.OesUploadPrekeys getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OesPreKeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OesPreKey)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 key_id = 1;</code>
     */
    long getKeyId();

    /**
     * <code>bytes public_key = 2;</code>
     */
    com.google.protobuf.ByteString getPublicKey();
  }
  /**
   * Protobuf type {@code OesPreKey}
   */
  public  static final class OesPreKey extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OesPreKey)
      OesPreKeyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OesPreKey.newBuilder() to construct.
    private OesPreKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OesPreKey() {
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OesPreKey(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              keyId_ = input.readInt64();
              break;
            }
            case 18: {

              publicKey_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.cowpi.protobuf.OesProto.internal_static_OesPreKey_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.cowpi.protobuf.OesProto.internal_static_OesPreKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.cowpi.protobuf.OesProto.OesPreKey.class, net.cowpi.protobuf.OesProto.OesPreKey.Builder.class);
    }

    public static final int KEY_ID_FIELD_NUMBER = 1;
    private long keyId_;
    /**
     * <code>int64 key_id = 1;</code>
     */
    public long getKeyId() {
      return keyId_;
    }

    public static final int PUBLIC_KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>bytes public_key = 2;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (keyId_ != 0L) {
        output.writeInt64(1, keyId_);
      }
      if (!publicKey_.isEmpty()) {
        output.writeBytes(2, publicKey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (keyId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, keyId_);
      }
      if (!publicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, publicKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.cowpi.protobuf.OesProto.OesPreKey)) {
        return super.equals(obj);
      }
      net.cowpi.protobuf.OesProto.OesPreKey other = (net.cowpi.protobuf.OesProto.OesPreKey) obj;

      if (getKeyId()
          != other.getKeyId()) return false;
      if (!getPublicKey()
          .equals(other.getPublicKey())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getKeyId());
      hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.cowpi.protobuf.OesProto.OesPreKey parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cowpi.protobuf.OesProto.OesPreKey parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesPreKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cowpi.protobuf.OesProto.OesPreKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesPreKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cowpi.protobuf.OesProto.OesPreKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesPreKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cowpi.protobuf.OesProto.OesPreKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesPreKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.cowpi.protobuf.OesProto.OesPreKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cowpi.protobuf.OesProto.OesPreKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cowpi.protobuf.OesProto.OesPreKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.cowpi.protobuf.OesProto.OesPreKey prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OesPreKey}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OesPreKey)
        net.cowpi.protobuf.OesProto.OesPreKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.cowpi.protobuf.OesProto.internal_static_OesPreKey_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.cowpi.protobuf.OesProto.internal_static_OesPreKey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.cowpi.protobuf.OesProto.OesPreKey.class, net.cowpi.protobuf.OesProto.OesPreKey.Builder.class);
      }

      // Construct using net.cowpi.protobuf.OesProto.OesPreKey.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        keyId_ = 0L;

        publicKey_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.cowpi.protobuf.OesProto.internal_static_OesPreKey_descriptor;
      }

      @java.lang.Override
      public net.cowpi.protobuf.OesProto.OesPreKey getDefaultInstanceForType() {
        return net.cowpi.protobuf.OesProto.OesPreKey.getDefaultInstance();
      }

      @java.lang.Override
      public net.cowpi.protobuf.OesProto.OesPreKey build() {
        net.cowpi.protobuf.OesProto.OesPreKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.cowpi.protobuf.OesProto.OesPreKey buildPartial() {
        net.cowpi.protobuf.OesProto.OesPreKey result = new net.cowpi.protobuf.OesProto.OesPreKey(this);
        result.keyId_ = keyId_;
        result.publicKey_ = publicKey_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.cowpi.protobuf.OesProto.OesPreKey) {
          return mergeFrom((net.cowpi.protobuf.OesProto.OesPreKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.cowpi.protobuf.OesProto.OesPreKey other) {
        if (other == net.cowpi.protobuf.OesProto.OesPreKey.getDefaultInstance()) return this;
        if (other.getKeyId() != 0L) {
          setKeyId(other.getKeyId());
        }
        if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
          setPublicKey(other.getPublicKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.cowpi.protobuf.OesProto.OesPreKey parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.cowpi.protobuf.OesProto.OesPreKey) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long keyId_ ;
      /**
       * <code>int64 key_id = 1;</code>
       */
      public long getKeyId() {
        return keyId_;
      }
      /**
       * <code>int64 key_id = 1;</code>
       */
      public Builder setKeyId(long value) {
        
        keyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 key_id = 1;</code>
       */
      public Builder clearKeyId() {
        
        keyId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes public_key = 2;</code>
       */
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>bytes public_key = 2;</code>
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes public_key = 2;</code>
       */
      public Builder clearPublicKey() {
        
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OesPreKey)
    }

    // @@protoc_insertion_point(class_scope:OesPreKey)
    private static final net.cowpi.protobuf.OesProto.OesPreKey DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.cowpi.protobuf.OesProto.OesPreKey();
    }

    public static net.cowpi.protobuf.OesProto.OesPreKey getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OesPreKey>
        PARSER = new com.google.protobuf.AbstractParser<OesPreKey>() {
      @java.lang.Override
      public OesPreKey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OesPreKey(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OesPreKey> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OesPreKey> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.cowpi.protobuf.OesProto.OesPreKey getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OesContainer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OesContainer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OesUploadPrekeys_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OesUploadPrekeys_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OesPreKey_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OesPreKey_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tOes.proto\032\rMessage.proto\"p\n\014OesContain" +
      "er\022/\n\022oes_upload_prekeys\030\001 \001(\0132\021.OesUplo" +
      "adPrekeysH\000\022&\n\rcowpi_message\030\002 \001(\0132\r.Cow" +
      "piMessageH\000B\007\n\005inner\"G\n\020OesUploadPrekeys" +
      "\022\023\n\013prekeyCount\030\001 \001(\005\022\036\n\noes_prekey\030\002 \003(" +
      "\0132\n.OesPreKey\"/\n\tOesPreKey\022\016\n\006key_id\030\001 \001" +
      "(\003\022\022\n\npublic_key\030\002 \001(\014B\036\n\022net.cowpi.prot" +
      "obufB\010OesProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.cowpi.protobuf.MessageProto.getDescriptor(),
        }, assigner);
    internal_static_OesContainer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OesContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OesContainer_descriptor,
        new java.lang.String[] { "OesUploadPrekeys", "CowpiMessage", "Inner", });
    internal_static_OesUploadPrekeys_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OesUploadPrekeys_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OesUploadPrekeys_descriptor,
        new java.lang.String[] { "PrekeyCount", "OesPrekey", });
    internal_static_OesPreKey_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OesPreKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OesPreKey_descriptor,
        new java.lang.String[] { "KeyId", "PublicKey", });
    net.cowpi.protobuf.MessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
