// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server.proto

package net.cowpi.protobuf;

public final class ServerProtos {
  private ServerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerContainerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServerContainer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>.UserContainer user_container = 2;</code>
     */
    boolean hasUserContainer();
    /**
     * <code>.UserContainer user_container = 2;</code>
     */
    net.cowpi.protobuf.UserProtos.UserContainer getUserContainer();
    /**
     * <code>.UserContainer user_container = 2;</code>
     */
    net.cowpi.protobuf.UserProtos.UserContainerOrBuilder getUserContainerOrBuilder();

    /**
     * <code>.CowpiMessage cowpi_message = 3;</code>
     */
    boolean hasCowpiMessage();
    /**
     * <code>.CowpiMessage cowpi_message = 3;</code>
     */
    net.cowpi.protobuf.MessageProto.CowpiMessage getCowpiMessage();
    /**
     * <code>.CowpiMessage cowpi_message = 3;</code>
     */
    net.cowpi.protobuf.MessageProto.CowpiMessageOrBuilder getCowpiMessageOrBuilder();

    /**
     * <code>.OesContainer oes_container = 4;</code>
     */
    boolean hasOesContainer();
    /**
     * <code>.OesContainer oes_container = 4;</code>
     */
    net.cowpi.protobuf.OesProto.OesContainer getOesContainer();
    /**
     * <code>.OesContainer oes_container = 4;</code>
     */
    net.cowpi.protobuf.OesProto.OesContainerOrBuilder getOesContainerOrBuilder();

    public net.cowpi.protobuf.ServerProtos.ServerContainer.InnerCase getInnerCase();
  }
  /**
   * Protobuf type {@code ServerContainer}
   */
  public  static final class ServerContainer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ServerContainer)
      ServerContainerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerContainer.newBuilder() to construct.
    private ServerContainer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerContainer() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerContainer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              net.cowpi.protobuf.UserProtos.UserContainer.Builder subBuilder = null;
              if (innerCase_ == 2) {
                subBuilder = ((net.cowpi.protobuf.UserProtos.UserContainer) inner_).toBuilder();
              }
              inner_ =
                  input.readMessage(net.cowpi.protobuf.UserProtos.UserContainer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((net.cowpi.protobuf.UserProtos.UserContainer) inner_);
                inner_ = subBuilder.buildPartial();
              }
              innerCase_ = 2;
              break;
            }
            case 26: {
              net.cowpi.protobuf.MessageProto.CowpiMessage.Builder subBuilder = null;
              if (innerCase_ == 3) {
                subBuilder = ((net.cowpi.protobuf.MessageProto.CowpiMessage) inner_).toBuilder();
              }
              inner_ =
                  input.readMessage(net.cowpi.protobuf.MessageProto.CowpiMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((net.cowpi.protobuf.MessageProto.CowpiMessage) inner_);
                inner_ = subBuilder.buildPartial();
              }
              innerCase_ = 3;
              break;
            }
            case 34: {
              net.cowpi.protobuf.OesProto.OesContainer.Builder subBuilder = null;
              if (innerCase_ == 4) {
                subBuilder = ((net.cowpi.protobuf.OesProto.OesContainer) inner_).toBuilder();
              }
              inner_ =
                  input.readMessage(net.cowpi.protobuf.OesProto.OesContainer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((net.cowpi.protobuf.OesProto.OesContainer) inner_);
                inner_ = subBuilder.buildPartial();
              }
              innerCase_ = 4;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.cowpi.protobuf.ServerProtos.internal_static_ServerContainer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.cowpi.protobuf.ServerProtos.internal_static_ServerContainer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.cowpi.protobuf.ServerProtos.ServerContainer.class, net.cowpi.protobuf.ServerProtos.ServerContainer.Builder.class);
    }

    private int innerCase_ = 0;
    private java.lang.Object inner_;
    public enum InnerCase
        implements com.google.protobuf.Internal.EnumLite {
      USER_CONTAINER(2),
      COWPI_MESSAGE(3),
      OES_CONTAINER(4),
      INNER_NOT_SET(0);
      private final int value;
      private InnerCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static InnerCase valueOf(int value) {
        return forNumber(value);
      }

      public static InnerCase forNumber(int value) {
        switch (value) {
          case 2: return USER_CONTAINER;
          case 3: return COWPI_MESSAGE;
          case 4: return OES_CONTAINER;
          case 0: return INNER_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public InnerCase
    getInnerCase() {
      return InnerCase.forNumber(
          innerCase_);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int USER_CONTAINER_FIELD_NUMBER = 2;
    /**
     * <code>.UserContainer user_container = 2;</code>
     */
    public boolean hasUserContainer() {
      return innerCase_ == 2;
    }
    /**
     * <code>.UserContainer user_container = 2;</code>
     */
    public net.cowpi.protobuf.UserProtos.UserContainer getUserContainer() {
      if (innerCase_ == 2) {
         return (net.cowpi.protobuf.UserProtos.UserContainer) inner_;
      }
      return net.cowpi.protobuf.UserProtos.UserContainer.getDefaultInstance();
    }
    /**
     * <code>.UserContainer user_container = 2;</code>
     */
    public net.cowpi.protobuf.UserProtos.UserContainerOrBuilder getUserContainerOrBuilder() {
      if (innerCase_ == 2) {
         return (net.cowpi.protobuf.UserProtos.UserContainer) inner_;
      }
      return net.cowpi.protobuf.UserProtos.UserContainer.getDefaultInstance();
    }

    public static final int COWPI_MESSAGE_FIELD_NUMBER = 3;
    /**
     * <code>.CowpiMessage cowpi_message = 3;</code>
     */
    public boolean hasCowpiMessage() {
      return innerCase_ == 3;
    }
    /**
     * <code>.CowpiMessage cowpi_message = 3;</code>
     */
    public net.cowpi.protobuf.MessageProto.CowpiMessage getCowpiMessage() {
      if (innerCase_ == 3) {
         return (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_;
      }
      return net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance();
    }
    /**
     * <code>.CowpiMessage cowpi_message = 3;</code>
     */
    public net.cowpi.protobuf.MessageProto.CowpiMessageOrBuilder getCowpiMessageOrBuilder() {
      if (innerCase_ == 3) {
         return (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_;
      }
      return net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance();
    }

    public static final int OES_CONTAINER_FIELD_NUMBER = 4;
    /**
     * <code>.OesContainer oes_container = 4;</code>
     */
    public boolean hasOesContainer() {
      return innerCase_ == 4;
    }
    /**
     * <code>.OesContainer oes_container = 4;</code>
     */
    public net.cowpi.protobuf.OesProto.OesContainer getOesContainer() {
      if (innerCase_ == 4) {
         return (net.cowpi.protobuf.OesProto.OesContainer) inner_;
      }
      return net.cowpi.protobuf.OesProto.OesContainer.getDefaultInstance();
    }
    /**
     * <code>.OesContainer oes_container = 4;</code>
     */
    public net.cowpi.protobuf.OesProto.OesContainerOrBuilder getOesContainerOrBuilder() {
      if (innerCase_ == 4) {
         return (net.cowpi.protobuf.OesProto.OesContainer) inner_;
      }
      return net.cowpi.protobuf.OesProto.OesContainer.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (innerCase_ == 2) {
        output.writeMessage(2, (net.cowpi.protobuf.UserProtos.UserContainer) inner_);
      }
      if (innerCase_ == 3) {
        output.writeMessage(3, (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_);
      }
      if (innerCase_ == 4) {
        output.writeMessage(4, (net.cowpi.protobuf.OesProto.OesContainer) inner_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (innerCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (net.cowpi.protobuf.UserProtos.UserContainer) inner_);
      }
      if (innerCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_);
      }
      if (innerCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (net.cowpi.protobuf.OesProto.OesContainer) inner_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.cowpi.protobuf.ServerProtos.ServerContainer)) {
        return super.equals(obj);
      }
      net.cowpi.protobuf.ServerProtos.ServerContainer other = (net.cowpi.protobuf.ServerProtos.ServerContainer) obj;

      if (getId()
          != other.getId()) return false;
      if (!getInnerCase().equals(other.getInnerCase())) return false;
      switch (innerCase_) {
        case 2:
          if (!getUserContainer()
              .equals(other.getUserContainer())) return false;
          break;
        case 3:
          if (!getCowpiMessage()
              .equals(other.getCowpiMessage())) return false;
          break;
        case 4:
          if (!getOesContainer()
              .equals(other.getOesContainer())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      switch (innerCase_) {
        case 2:
          hash = (37 * hash) + USER_CONTAINER_FIELD_NUMBER;
          hash = (53 * hash) + getUserContainer().hashCode();
          break;
        case 3:
          hash = (37 * hash) + COWPI_MESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getCowpiMessage().hashCode();
          break;
        case 4:
          hash = (37 * hash) + OES_CONTAINER_FIELD_NUMBER;
          hash = (53 * hash) + getOesContainer().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.cowpi.protobuf.ServerProtos.ServerContainer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cowpi.protobuf.ServerProtos.ServerContainer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cowpi.protobuf.ServerProtos.ServerContainer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cowpi.protobuf.ServerProtos.ServerContainer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cowpi.protobuf.ServerProtos.ServerContainer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cowpi.protobuf.ServerProtos.ServerContainer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cowpi.protobuf.ServerProtos.ServerContainer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cowpi.protobuf.ServerProtos.ServerContainer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cowpi.protobuf.ServerProtos.ServerContainer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.cowpi.protobuf.ServerProtos.ServerContainer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cowpi.protobuf.ServerProtos.ServerContainer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cowpi.protobuf.ServerProtos.ServerContainer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.cowpi.protobuf.ServerProtos.ServerContainer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerContainer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServerContainer)
        net.cowpi.protobuf.ServerProtos.ServerContainerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.cowpi.protobuf.ServerProtos.internal_static_ServerContainer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.cowpi.protobuf.ServerProtos.internal_static_ServerContainer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.cowpi.protobuf.ServerProtos.ServerContainer.class, net.cowpi.protobuf.ServerProtos.ServerContainer.Builder.class);
      }

      // Construct using net.cowpi.protobuf.ServerProtos.ServerContainer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        innerCase_ = 0;
        inner_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.cowpi.protobuf.ServerProtos.internal_static_ServerContainer_descriptor;
      }

      @java.lang.Override
      public net.cowpi.protobuf.ServerProtos.ServerContainer getDefaultInstanceForType() {
        return net.cowpi.protobuf.ServerProtos.ServerContainer.getDefaultInstance();
      }

      @java.lang.Override
      public net.cowpi.protobuf.ServerProtos.ServerContainer build() {
        net.cowpi.protobuf.ServerProtos.ServerContainer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.cowpi.protobuf.ServerProtos.ServerContainer buildPartial() {
        net.cowpi.protobuf.ServerProtos.ServerContainer result = new net.cowpi.protobuf.ServerProtos.ServerContainer(this);
        result.id_ = id_;
        if (innerCase_ == 2) {
          if (userContainerBuilder_ == null) {
            result.inner_ = inner_;
          } else {
            result.inner_ = userContainerBuilder_.build();
          }
        }
        if (innerCase_ == 3) {
          if (cowpiMessageBuilder_ == null) {
            result.inner_ = inner_;
          } else {
            result.inner_ = cowpiMessageBuilder_.build();
          }
        }
        if (innerCase_ == 4) {
          if (oesContainerBuilder_ == null) {
            result.inner_ = inner_;
          } else {
            result.inner_ = oesContainerBuilder_.build();
          }
        }
        result.innerCase_ = innerCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.cowpi.protobuf.ServerProtos.ServerContainer) {
          return mergeFrom((net.cowpi.protobuf.ServerProtos.ServerContainer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.cowpi.protobuf.ServerProtos.ServerContainer other) {
        if (other == net.cowpi.protobuf.ServerProtos.ServerContainer.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        switch (other.getInnerCase()) {
          case USER_CONTAINER: {
            mergeUserContainer(other.getUserContainer());
            break;
          }
          case COWPI_MESSAGE: {
            mergeCowpiMessage(other.getCowpiMessage());
            break;
          }
          case OES_CONTAINER: {
            mergeOesContainer(other.getOesContainer());
            break;
          }
          case INNER_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.cowpi.protobuf.ServerProtos.ServerContainer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.cowpi.protobuf.ServerProtos.ServerContainer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int innerCase_ = 0;
      private java.lang.Object inner_;
      public InnerCase
          getInnerCase() {
        return InnerCase.forNumber(
            innerCase_);
      }

      public Builder clearInner() {
        innerCase_ = 0;
        inner_ = null;
        onChanged();
        return this;
      }


      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          net.cowpi.protobuf.UserProtos.UserContainer, net.cowpi.protobuf.UserProtos.UserContainer.Builder, net.cowpi.protobuf.UserProtos.UserContainerOrBuilder> userContainerBuilder_;
      /**
       * <code>.UserContainer user_container = 2;</code>
       */
      public boolean hasUserContainer() {
        return innerCase_ == 2;
      }
      /**
       * <code>.UserContainer user_container = 2;</code>
       */
      public net.cowpi.protobuf.UserProtos.UserContainer getUserContainer() {
        if (userContainerBuilder_ == null) {
          if (innerCase_ == 2) {
            return (net.cowpi.protobuf.UserProtos.UserContainer) inner_;
          }
          return net.cowpi.protobuf.UserProtos.UserContainer.getDefaultInstance();
        } else {
          if (innerCase_ == 2) {
            return userContainerBuilder_.getMessage();
          }
          return net.cowpi.protobuf.UserProtos.UserContainer.getDefaultInstance();
        }
      }
      /**
       * <code>.UserContainer user_container = 2;</code>
       */
      public Builder setUserContainer(net.cowpi.protobuf.UserProtos.UserContainer value) {
        if (userContainerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          inner_ = value;
          onChanged();
        } else {
          userContainerBuilder_.setMessage(value);
        }
        innerCase_ = 2;
        return this;
      }
      /**
       * <code>.UserContainer user_container = 2;</code>
       */
      public Builder setUserContainer(
          net.cowpi.protobuf.UserProtos.UserContainer.Builder builderForValue) {
        if (userContainerBuilder_ == null) {
          inner_ = builderForValue.build();
          onChanged();
        } else {
          userContainerBuilder_.setMessage(builderForValue.build());
        }
        innerCase_ = 2;
        return this;
      }
      /**
       * <code>.UserContainer user_container = 2;</code>
       */
      public Builder mergeUserContainer(net.cowpi.protobuf.UserProtos.UserContainer value) {
        if (userContainerBuilder_ == null) {
          if (innerCase_ == 2 &&
              inner_ != net.cowpi.protobuf.UserProtos.UserContainer.getDefaultInstance()) {
            inner_ = net.cowpi.protobuf.UserProtos.UserContainer.newBuilder((net.cowpi.protobuf.UserProtos.UserContainer) inner_)
                .mergeFrom(value).buildPartial();
          } else {
            inner_ = value;
          }
          onChanged();
        } else {
          if (innerCase_ == 2) {
            userContainerBuilder_.mergeFrom(value);
          }
          userContainerBuilder_.setMessage(value);
        }
        innerCase_ = 2;
        return this;
      }
      /**
       * <code>.UserContainer user_container = 2;</code>
       */
      public Builder clearUserContainer() {
        if (userContainerBuilder_ == null) {
          if (innerCase_ == 2) {
            innerCase_ = 0;
            inner_ = null;
            onChanged();
          }
        } else {
          if (innerCase_ == 2) {
            innerCase_ = 0;
            inner_ = null;
          }
          userContainerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.UserContainer user_container = 2;</code>
       */
      public net.cowpi.protobuf.UserProtos.UserContainer.Builder getUserContainerBuilder() {
        return getUserContainerFieldBuilder().getBuilder();
      }
      /**
       * <code>.UserContainer user_container = 2;</code>
       */
      public net.cowpi.protobuf.UserProtos.UserContainerOrBuilder getUserContainerOrBuilder() {
        if ((innerCase_ == 2) && (userContainerBuilder_ != null)) {
          return userContainerBuilder_.getMessageOrBuilder();
        } else {
          if (innerCase_ == 2) {
            return (net.cowpi.protobuf.UserProtos.UserContainer) inner_;
          }
          return net.cowpi.protobuf.UserProtos.UserContainer.getDefaultInstance();
        }
      }
      /**
       * <code>.UserContainer user_container = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.cowpi.protobuf.UserProtos.UserContainer, net.cowpi.protobuf.UserProtos.UserContainer.Builder, net.cowpi.protobuf.UserProtos.UserContainerOrBuilder> 
          getUserContainerFieldBuilder() {
        if (userContainerBuilder_ == null) {
          if (!(innerCase_ == 2)) {
            inner_ = net.cowpi.protobuf.UserProtos.UserContainer.getDefaultInstance();
          }
          userContainerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.cowpi.protobuf.UserProtos.UserContainer, net.cowpi.protobuf.UserProtos.UserContainer.Builder, net.cowpi.protobuf.UserProtos.UserContainerOrBuilder>(
                  (net.cowpi.protobuf.UserProtos.UserContainer) inner_,
                  getParentForChildren(),
                  isClean());
          inner_ = null;
        }
        innerCase_ = 2;
        onChanged();;
        return userContainerBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          net.cowpi.protobuf.MessageProto.CowpiMessage, net.cowpi.protobuf.MessageProto.CowpiMessage.Builder, net.cowpi.protobuf.MessageProto.CowpiMessageOrBuilder> cowpiMessageBuilder_;
      /**
       * <code>.CowpiMessage cowpi_message = 3;</code>
       */
      public boolean hasCowpiMessage() {
        return innerCase_ == 3;
      }
      /**
       * <code>.CowpiMessage cowpi_message = 3;</code>
       */
      public net.cowpi.protobuf.MessageProto.CowpiMessage getCowpiMessage() {
        if (cowpiMessageBuilder_ == null) {
          if (innerCase_ == 3) {
            return (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_;
          }
          return net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance();
        } else {
          if (innerCase_ == 3) {
            return cowpiMessageBuilder_.getMessage();
          }
          return net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.CowpiMessage cowpi_message = 3;</code>
       */
      public Builder setCowpiMessage(net.cowpi.protobuf.MessageProto.CowpiMessage value) {
        if (cowpiMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          inner_ = value;
          onChanged();
        } else {
          cowpiMessageBuilder_.setMessage(value);
        }
        innerCase_ = 3;
        return this;
      }
      /**
       * <code>.CowpiMessage cowpi_message = 3;</code>
       */
      public Builder setCowpiMessage(
          net.cowpi.protobuf.MessageProto.CowpiMessage.Builder builderForValue) {
        if (cowpiMessageBuilder_ == null) {
          inner_ = builderForValue.build();
          onChanged();
        } else {
          cowpiMessageBuilder_.setMessage(builderForValue.build());
        }
        innerCase_ = 3;
        return this;
      }
      /**
       * <code>.CowpiMessage cowpi_message = 3;</code>
       */
      public Builder mergeCowpiMessage(net.cowpi.protobuf.MessageProto.CowpiMessage value) {
        if (cowpiMessageBuilder_ == null) {
          if (innerCase_ == 3 &&
              inner_ != net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance()) {
            inner_ = net.cowpi.protobuf.MessageProto.CowpiMessage.newBuilder((net.cowpi.protobuf.MessageProto.CowpiMessage) inner_)
                .mergeFrom(value).buildPartial();
          } else {
            inner_ = value;
          }
          onChanged();
        } else {
          if (innerCase_ == 3) {
            cowpiMessageBuilder_.mergeFrom(value);
          }
          cowpiMessageBuilder_.setMessage(value);
        }
        innerCase_ = 3;
        return this;
      }
      /**
       * <code>.CowpiMessage cowpi_message = 3;</code>
       */
      public Builder clearCowpiMessage() {
        if (cowpiMessageBuilder_ == null) {
          if (innerCase_ == 3) {
            innerCase_ = 0;
            inner_ = null;
            onChanged();
          }
        } else {
          if (innerCase_ == 3) {
            innerCase_ = 0;
            inner_ = null;
          }
          cowpiMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.CowpiMessage cowpi_message = 3;</code>
       */
      public net.cowpi.protobuf.MessageProto.CowpiMessage.Builder getCowpiMessageBuilder() {
        return getCowpiMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.CowpiMessage cowpi_message = 3;</code>
       */
      public net.cowpi.protobuf.MessageProto.CowpiMessageOrBuilder getCowpiMessageOrBuilder() {
        if ((innerCase_ == 3) && (cowpiMessageBuilder_ != null)) {
          return cowpiMessageBuilder_.getMessageOrBuilder();
        } else {
          if (innerCase_ == 3) {
            return (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_;
          }
          return net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.CowpiMessage cowpi_message = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.cowpi.protobuf.MessageProto.CowpiMessage, net.cowpi.protobuf.MessageProto.CowpiMessage.Builder, net.cowpi.protobuf.MessageProto.CowpiMessageOrBuilder> 
          getCowpiMessageFieldBuilder() {
        if (cowpiMessageBuilder_ == null) {
          if (!(innerCase_ == 3)) {
            inner_ = net.cowpi.protobuf.MessageProto.CowpiMessage.getDefaultInstance();
          }
          cowpiMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.cowpi.protobuf.MessageProto.CowpiMessage, net.cowpi.protobuf.MessageProto.CowpiMessage.Builder, net.cowpi.protobuf.MessageProto.CowpiMessageOrBuilder>(
                  (net.cowpi.protobuf.MessageProto.CowpiMessage) inner_,
                  getParentForChildren(),
                  isClean());
          inner_ = null;
        }
        innerCase_ = 3;
        onChanged();;
        return cowpiMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          net.cowpi.protobuf.OesProto.OesContainer, net.cowpi.protobuf.OesProto.OesContainer.Builder, net.cowpi.protobuf.OesProto.OesContainerOrBuilder> oesContainerBuilder_;
      /**
       * <code>.OesContainer oes_container = 4;</code>
       */
      public boolean hasOesContainer() {
        return innerCase_ == 4;
      }
      /**
       * <code>.OesContainer oes_container = 4;</code>
       */
      public net.cowpi.protobuf.OesProto.OesContainer getOesContainer() {
        if (oesContainerBuilder_ == null) {
          if (innerCase_ == 4) {
            return (net.cowpi.protobuf.OesProto.OesContainer) inner_;
          }
          return net.cowpi.protobuf.OesProto.OesContainer.getDefaultInstance();
        } else {
          if (innerCase_ == 4) {
            return oesContainerBuilder_.getMessage();
          }
          return net.cowpi.protobuf.OesProto.OesContainer.getDefaultInstance();
        }
      }
      /**
       * <code>.OesContainer oes_container = 4;</code>
       */
      public Builder setOesContainer(net.cowpi.protobuf.OesProto.OesContainer value) {
        if (oesContainerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          inner_ = value;
          onChanged();
        } else {
          oesContainerBuilder_.setMessage(value);
        }
        innerCase_ = 4;
        return this;
      }
      /**
       * <code>.OesContainer oes_container = 4;</code>
       */
      public Builder setOesContainer(
          net.cowpi.protobuf.OesProto.OesContainer.Builder builderForValue) {
        if (oesContainerBuilder_ == null) {
          inner_ = builderForValue.build();
          onChanged();
        } else {
          oesContainerBuilder_.setMessage(builderForValue.build());
        }
        innerCase_ = 4;
        return this;
      }
      /**
       * <code>.OesContainer oes_container = 4;</code>
       */
      public Builder mergeOesContainer(net.cowpi.protobuf.OesProto.OesContainer value) {
        if (oesContainerBuilder_ == null) {
          if (innerCase_ == 4 &&
              inner_ != net.cowpi.protobuf.OesProto.OesContainer.getDefaultInstance()) {
            inner_ = net.cowpi.protobuf.OesProto.OesContainer.newBuilder((net.cowpi.protobuf.OesProto.OesContainer) inner_)
                .mergeFrom(value).buildPartial();
          } else {
            inner_ = value;
          }
          onChanged();
        } else {
          if (innerCase_ == 4) {
            oesContainerBuilder_.mergeFrom(value);
          }
          oesContainerBuilder_.setMessage(value);
        }
        innerCase_ = 4;
        return this;
      }
      /**
       * <code>.OesContainer oes_container = 4;</code>
       */
      public Builder clearOesContainer() {
        if (oesContainerBuilder_ == null) {
          if (innerCase_ == 4) {
            innerCase_ = 0;
            inner_ = null;
            onChanged();
          }
        } else {
          if (innerCase_ == 4) {
            innerCase_ = 0;
            inner_ = null;
          }
          oesContainerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.OesContainer oes_container = 4;</code>
       */
      public net.cowpi.protobuf.OesProto.OesContainer.Builder getOesContainerBuilder() {
        return getOesContainerFieldBuilder().getBuilder();
      }
      /**
       * <code>.OesContainer oes_container = 4;</code>
       */
      public net.cowpi.protobuf.OesProto.OesContainerOrBuilder getOesContainerOrBuilder() {
        if ((innerCase_ == 4) && (oesContainerBuilder_ != null)) {
          return oesContainerBuilder_.getMessageOrBuilder();
        } else {
          if (innerCase_ == 4) {
            return (net.cowpi.protobuf.OesProto.OesContainer) inner_;
          }
          return net.cowpi.protobuf.OesProto.OesContainer.getDefaultInstance();
        }
      }
      /**
       * <code>.OesContainer oes_container = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.cowpi.protobuf.OesProto.OesContainer, net.cowpi.protobuf.OesProto.OesContainer.Builder, net.cowpi.protobuf.OesProto.OesContainerOrBuilder> 
          getOesContainerFieldBuilder() {
        if (oesContainerBuilder_ == null) {
          if (!(innerCase_ == 4)) {
            inner_ = net.cowpi.protobuf.OesProto.OesContainer.getDefaultInstance();
          }
          oesContainerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.cowpi.protobuf.OesProto.OesContainer, net.cowpi.protobuf.OesProto.OesContainer.Builder, net.cowpi.protobuf.OesProto.OesContainerOrBuilder>(
                  (net.cowpi.protobuf.OesProto.OesContainer) inner_,
                  getParentForChildren(),
                  isClean());
          inner_ = null;
        }
        innerCase_ = 4;
        onChanged();;
        return oesContainerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ServerContainer)
    }

    // @@protoc_insertion_point(class_scope:ServerContainer)
    private static final net.cowpi.protobuf.ServerProtos.ServerContainer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.cowpi.protobuf.ServerProtos.ServerContainer();
    }

    public static net.cowpi.protobuf.ServerProtos.ServerContainer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerContainer>
        PARSER = new com.google.protobuf.AbstractParser<ServerContainer>() {
      @java.lang.Override
      public ServerContainer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerContainer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerContainer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerContainer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.cowpi.protobuf.ServerProtos.ServerContainer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerContainer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerContainer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Server.proto\032\nUser.proto\032\rMessage.prot" +
      "o\032\tOes.proto\"\240\001\n\017ServerContainer\022\n\n\002id\030\001" +
      " \001(\005\022(\n\016user_container\030\002 \001(\0132\016.UserConta" +
      "inerH\000\022&\n\rcowpi_message\030\003 \001(\0132\r.CowpiMes" +
      "sageH\000\022&\n\roes_container\030\004 \001(\0132\r.OesConta" +
      "inerH\000B\007\n\005innerB\"\n\022net.cowpi.protobufB\014S" +
      "erverProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.cowpi.protobuf.UserProtos.getDescriptor(),
          net.cowpi.protobuf.MessageProto.getDescriptor(),
          net.cowpi.protobuf.OesProto.getDescriptor(),
        }, assigner);
    internal_static_ServerContainer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServerContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerContainer_descriptor,
        new java.lang.String[] { "Id", "UserContainer", "CowpiMessage", "OesContainer", "Inner", });
    net.cowpi.protobuf.UserProtos.getDescriptor();
    net.cowpi.protobuf.MessageProto.getDescriptor();
    net.cowpi.protobuf.OesProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
