/*
 * This file is generated by jOOQ.
 */
package net.cowpi.oes.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import net.cowpi.oes.jooq.tables.Conversation;
import net.cowpi.oes.jooq.tables.LocalKey;
import net.cowpi.oes.jooq.tables.ParticipantState;
import net.cowpi.oes.jooq.tables.Prekey;
import net.cowpi.oes.jooq.tables.RouterMailbox;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -1449552754;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>conversation</code>.
     */
    public final Conversation CONVERSATION = net.cowpi.oes.jooq.tables.Conversation.CONVERSATION;

    /**
     * The table <code>local_key</code>.
     */
    public final LocalKey LOCAL_KEY = net.cowpi.oes.jooq.tables.LocalKey.LOCAL_KEY;

    /**
     * The table <code>participant_state</code>.
     */
    public final ParticipantState PARTICIPANT_STATE = net.cowpi.oes.jooq.tables.ParticipantState.PARTICIPANT_STATE;

    /**
     * The table <code>prekey</code>.
     */
    public final Prekey PREKEY = net.cowpi.oes.jooq.tables.Prekey.PREKEY;

    /**
     * The table <code>router_mailbox</code>.
     */
    public final RouterMailbox ROUTER_MAILBOX = net.cowpi.oes.jooq.tables.RouterMailbox.ROUTER_MAILBOX;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CONVERSATION_ID_SEQ,
            Sequences.LOCAL_KEY_ID_SEQ,
            Sequences.PARTICIPANT_STATE_ID_SEQ,
            Sequences.PREKEY_ID_SEQ,
            Sequences.ROUTER_MAILBOX_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Conversation.CONVERSATION,
            LocalKey.LOCAL_KEY,
            ParticipantState.PARTICIPANT_STATE,
            Prekey.PREKEY,
            RouterMailbox.ROUTER_MAILBOX);
    }
}
