/*
 * This file is generated by jOOQ.
 */
package net.cowpi.oes.jooq;


import javax.annotation.Generated;

import net.cowpi.oes.jooq.tables.Conversation;
import net.cowpi.oes.jooq.tables.LocalKey;
import net.cowpi.oes.jooq.tables.ParticipantState;
import net.cowpi.oes.jooq.tables.Prekey;
import net.cowpi.oes.jooq.tables.RouterMailbox;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONVERSATION_CONVERSATION_ID_KEY = Indexes0.CONVERSATION_CONVERSATION_ID_KEY;
    public static final Index CONVERSATION_PKEY = Indexes0.CONVERSATION_PKEY;
    public static final Index LOCAL_KEY_PKEY = Indexes0.LOCAL_KEY_PKEY;
    public static final Index LOCAL_KEY_STATE_LOCAL_EPHEMERAL_KEY_ID_KEY = Indexes0.LOCAL_KEY_STATE_LOCAL_EPHEMERAL_KEY_ID_KEY;
    public static final Index PARTICIPANT_STATE_CONVERSATION_USERNAME_KEY = Indexes0.PARTICIPANT_STATE_CONVERSATION_USERNAME_KEY;
    public static final Index PARTICIPANT_STATE_PKEY = Indexes0.PARTICIPANT_STATE_PKEY;
    public static final Index PREKEY_PKEY = Indexes0.PREKEY_PKEY;
    public static final Index ROUTER_MAILBOX_CONVERSATION_MESSAGE_INDEX_KEY = Indexes0.ROUTER_MAILBOX_CONVERSATION_MESSAGE_INDEX_KEY;
    public static final Index ROUTER_MAILBOX_PKEY = Indexes0.ROUTER_MAILBOX_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONVERSATION_CONVERSATION_ID_KEY = Internal.createIndex("conversation_conversation_id_key", Conversation.CONVERSATION, new OrderField[] { Conversation.CONVERSATION.CONVERSATION_ID }, true);
        public static Index CONVERSATION_PKEY = Internal.createIndex("conversation_pkey", Conversation.CONVERSATION, new OrderField[] { Conversation.CONVERSATION.ID }, true);
        public static Index LOCAL_KEY_PKEY = Internal.createIndex("local_key_pkey", LocalKey.LOCAL_KEY, new OrderField[] { LocalKey.LOCAL_KEY.ID }, true);
        public static Index LOCAL_KEY_STATE_LOCAL_EPHEMERAL_KEY_ID_KEY = Internal.createIndex("local_key_state_local_ephemeral_key_id_key", LocalKey.LOCAL_KEY, new OrderField[] { LocalKey.LOCAL_KEY.STATE, LocalKey.LOCAL_KEY.LOCAL_EPHEMERAL_KEY_ID }, true);
        public static Index PARTICIPANT_STATE_CONVERSATION_USERNAME_KEY = Internal.createIndex("participant_state_conversation_username_key", ParticipantState.PARTICIPANT_STATE, new OrderField[] { ParticipantState.PARTICIPANT_STATE.CONVERSATION, ParticipantState.PARTICIPANT_STATE.USERNAME }, true);
        public static Index PARTICIPANT_STATE_PKEY = Internal.createIndex("participant_state_pkey", ParticipantState.PARTICIPANT_STATE, new OrderField[] { ParticipantState.PARTICIPANT_STATE.ID }, true);
        public static Index PREKEY_PKEY = Internal.createIndex("prekey_pkey", Prekey.PREKEY, new OrderField[] { Prekey.PREKEY.ID }, true);
        public static Index ROUTER_MAILBOX_CONVERSATION_MESSAGE_INDEX_KEY = Internal.createIndex("router_mailbox_conversation_message_index_key", RouterMailbox.ROUTER_MAILBOX, new OrderField[] { RouterMailbox.ROUTER_MAILBOX.CONVERSATION, RouterMailbox.ROUTER_MAILBOX.MESSAGE_INDEX }, true);
        public static Index ROUTER_MAILBOX_PKEY = Internal.createIndex("router_mailbox_pkey", RouterMailbox.ROUTER_MAILBOX, new OrderField[] { RouterMailbox.ROUTER_MAILBOX.ID }, true);
    }
}
