/*
 * This file is generated by jOOQ.
 */
package net.cowpi.oes.jooq;


import javax.annotation.Generated;

import net.cowpi.oes.jooq.tables.Conversation;
import net.cowpi.oes.jooq.tables.LocalKey;
import net.cowpi.oes.jooq.tables.ParticipantState;
import net.cowpi.oes.jooq.tables.Prekey;
import net.cowpi.oes.jooq.tables.RouterMailbox;
import net.cowpi.oes.jooq.tables.records.ConversationRecord;
import net.cowpi.oes.jooq.tables.records.LocalKeyRecord;
import net.cowpi.oes.jooq.tables.records.ParticipantStateRecord;
import net.cowpi.oes.jooq.tables.records.PrekeyRecord;
import net.cowpi.oes.jooq.tables.records.RouterMailboxRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ConversationRecord, Long> IDENTITY_CONVERSATION = Identities0.IDENTITY_CONVERSATION;
    public static final Identity<LocalKeyRecord, Long> IDENTITY_LOCAL_KEY = Identities0.IDENTITY_LOCAL_KEY;
    public static final Identity<ParticipantStateRecord, Long> IDENTITY_PARTICIPANT_STATE = Identities0.IDENTITY_PARTICIPANT_STATE;
    public static final Identity<PrekeyRecord, Long> IDENTITY_PREKEY = Identities0.IDENTITY_PREKEY;
    public static final Identity<RouterMailboxRecord, Long> IDENTITY_ROUTER_MAILBOX = Identities0.IDENTITY_ROUTER_MAILBOX;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ConversationRecord> CONVERSATION_PKEY = UniqueKeys0.CONVERSATION_PKEY;
    public static final UniqueKey<ConversationRecord> CONVERSATION_CONVERSATION_ID_KEY = UniqueKeys0.CONVERSATION_CONVERSATION_ID_KEY;
    public static final UniqueKey<LocalKeyRecord> LOCAL_KEY_PKEY = UniqueKeys0.LOCAL_KEY_PKEY;
    public static final UniqueKey<LocalKeyRecord> LOCAL_KEY_STATE_LOCAL_EPHEMERAL_KEY_ID_KEY = UniqueKeys0.LOCAL_KEY_STATE_LOCAL_EPHEMERAL_KEY_ID_KEY;
    public static final UniqueKey<ParticipantStateRecord> PARTICIPANT_STATE_PKEY = UniqueKeys0.PARTICIPANT_STATE_PKEY;
    public static final UniqueKey<ParticipantStateRecord> PARTICIPANT_STATE_CONVERSATION_USERNAME_KEY = UniqueKeys0.PARTICIPANT_STATE_CONVERSATION_USERNAME_KEY;
    public static final UniqueKey<PrekeyRecord> PREKEY_PKEY = UniqueKeys0.PREKEY_PKEY;
    public static final UniqueKey<RouterMailboxRecord> ROUTER_MAILBOX_PKEY = UniqueKeys0.ROUTER_MAILBOX_PKEY;
    public static final UniqueKey<RouterMailboxRecord> ROUTER_MAILBOX_CONVERSATION_MESSAGE_INDEX_KEY = UniqueKeys0.ROUTER_MAILBOX_CONVERSATION_MESSAGE_INDEX_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LocalKeyRecord, ParticipantStateRecord> LOCAL_KEY__LOCAL_KEY_STATE_FKEY = ForeignKeys0.LOCAL_KEY__LOCAL_KEY_STATE_FKEY;
    public static final ForeignKey<ParticipantStateRecord, ConversationRecord> PARTICIPANT_STATE__PARTICIPANT_STATE_CONVERSATION_FKEY = ForeignKeys0.PARTICIPANT_STATE__PARTICIPANT_STATE_CONVERSATION_FKEY;
    public static final ForeignKey<RouterMailboxRecord, ConversationRecord> ROUTER_MAILBOX__ROUTER_MAILBOX_CONVERSATION_FKEY = ForeignKeys0.ROUTER_MAILBOX__ROUTER_MAILBOX_CONVERSATION_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ConversationRecord, Long> IDENTITY_CONVERSATION = Internal.createIdentity(Conversation.CONVERSATION, Conversation.CONVERSATION.ID);
        public static Identity<LocalKeyRecord, Long> IDENTITY_LOCAL_KEY = Internal.createIdentity(LocalKey.LOCAL_KEY, LocalKey.LOCAL_KEY.ID);
        public static Identity<ParticipantStateRecord, Long> IDENTITY_PARTICIPANT_STATE = Internal.createIdentity(ParticipantState.PARTICIPANT_STATE, ParticipantState.PARTICIPANT_STATE.ID);
        public static Identity<PrekeyRecord, Long> IDENTITY_PREKEY = Internal.createIdentity(Prekey.PREKEY, Prekey.PREKEY.ID);
        public static Identity<RouterMailboxRecord, Long> IDENTITY_ROUTER_MAILBOX = Internal.createIdentity(RouterMailbox.ROUTER_MAILBOX, RouterMailbox.ROUTER_MAILBOX.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ConversationRecord> CONVERSATION_PKEY = Internal.createUniqueKey(Conversation.CONVERSATION, "conversation_pkey", Conversation.CONVERSATION.ID);
        public static final UniqueKey<ConversationRecord> CONVERSATION_CONVERSATION_ID_KEY = Internal.createUniqueKey(Conversation.CONVERSATION, "conversation_conversation_id_key", Conversation.CONVERSATION.CONVERSATION_ID);
        public static final UniqueKey<LocalKeyRecord> LOCAL_KEY_PKEY = Internal.createUniqueKey(LocalKey.LOCAL_KEY, "local_key_pkey", LocalKey.LOCAL_KEY.ID);
        public static final UniqueKey<LocalKeyRecord> LOCAL_KEY_STATE_LOCAL_EPHEMERAL_KEY_ID_KEY = Internal.createUniqueKey(LocalKey.LOCAL_KEY, "local_key_state_local_ephemeral_key_id_key", LocalKey.LOCAL_KEY.STATE, LocalKey.LOCAL_KEY.LOCAL_EPHEMERAL_KEY_ID);
        public static final UniqueKey<ParticipantStateRecord> PARTICIPANT_STATE_PKEY = Internal.createUniqueKey(ParticipantState.PARTICIPANT_STATE, "participant_state_pkey", ParticipantState.PARTICIPANT_STATE.ID);
        public static final UniqueKey<ParticipantStateRecord> PARTICIPANT_STATE_CONVERSATION_USERNAME_KEY = Internal.createUniqueKey(ParticipantState.PARTICIPANT_STATE, "participant_state_conversation_username_key", ParticipantState.PARTICIPANT_STATE.CONVERSATION, ParticipantState.PARTICIPANT_STATE.USERNAME);
        public static final UniqueKey<PrekeyRecord> PREKEY_PKEY = Internal.createUniqueKey(Prekey.PREKEY, "prekey_pkey", Prekey.PREKEY.ID);
        public static final UniqueKey<RouterMailboxRecord> ROUTER_MAILBOX_PKEY = Internal.createUniqueKey(RouterMailbox.ROUTER_MAILBOX, "router_mailbox_pkey", RouterMailbox.ROUTER_MAILBOX.ID);
        public static final UniqueKey<RouterMailboxRecord> ROUTER_MAILBOX_CONVERSATION_MESSAGE_INDEX_KEY = Internal.createUniqueKey(RouterMailbox.ROUTER_MAILBOX, "router_mailbox_conversation_message_index_key", RouterMailbox.ROUTER_MAILBOX.CONVERSATION, RouterMailbox.ROUTER_MAILBOX.MESSAGE_INDEX);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<LocalKeyRecord, ParticipantStateRecord> LOCAL_KEY__LOCAL_KEY_STATE_FKEY = Internal.createForeignKey(net.cowpi.oes.jooq.Keys.PARTICIPANT_STATE_PKEY, LocalKey.LOCAL_KEY, "local_key__local_key_state_fkey", LocalKey.LOCAL_KEY.STATE);
        public static final ForeignKey<ParticipantStateRecord, ConversationRecord> PARTICIPANT_STATE__PARTICIPANT_STATE_CONVERSATION_FKEY = Internal.createForeignKey(net.cowpi.oes.jooq.Keys.CONVERSATION_PKEY, ParticipantState.PARTICIPANT_STATE, "participant_state__participant_state_conversation_fkey", ParticipantState.PARTICIPANT_STATE.CONVERSATION);
        public static final ForeignKey<RouterMailboxRecord, ConversationRecord> ROUTER_MAILBOX__ROUTER_MAILBOX_CONVERSATION_FKEY = Internal.createForeignKey(net.cowpi.oes.jooq.Keys.CONVERSATION_PKEY, RouterMailbox.ROUTER_MAILBOX, "router_mailbox__router_mailbox_conversation_fkey", RouterMailbox.ROUTER_MAILBOX.CONVERSATION);
    }
}
