/*
 * This file is generated by jOOQ.
 */
package net.cowpi.server.jooq;


import javax.annotation.Generated;

import net.cowpi.server.jooq.tables.ConversationMessage;
import net.cowpi.server.jooq.tables.CowpiUser;
import net.cowpi.server.jooq.tables.Mailbox;
import net.cowpi.server.jooq.tables.OesMessage;
import net.cowpi.server.jooq.tables.OesPrekey;
import net.cowpi.server.jooq.tables.OesService;
import net.cowpi.server.jooq.tables.Prekey;
import net.cowpi.server.jooq.tables.records.ConversationMessageRecord;
import net.cowpi.server.jooq.tables.records.CowpiUserRecord;
import net.cowpi.server.jooq.tables.records.MailboxRecord;
import net.cowpi.server.jooq.tables.records.OesMessageRecord;
import net.cowpi.server.jooq.tables.records.OesPrekeyRecord;
import net.cowpi.server.jooq.tables.records.OesServiceRecord;
import net.cowpi.server.jooq.tables.records.PrekeyRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>router</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ConversationMessageRecord, Long> IDENTITY_CONVERSATION_MESSAGE = Identities0.IDENTITY_CONVERSATION_MESSAGE;
    public static final Identity<CowpiUserRecord, Long> IDENTITY_COWPI_USER = Identities0.IDENTITY_COWPI_USER;
    public static final Identity<MailboxRecord, Long> IDENTITY_MAILBOX = Identities0.IDENTITY_MAILBOX;
    public static final Identity<OesMessageRecord, Long> IDENTITY_OES_MESSAGE = Identities0.IDENTITY_OES_MESSAGE;
    public static final Identity<OesPrekeyRecord, Long> IDENTITY_OES_PREKEY = Identities0.IDENTITY_OES_PREKEY;
    public static final Identity<OesServiceRecord, Long> IDENTITY_OES_SERVICE = Identities0.IDENTITY_OES_SERVICE;
    public static final Identity<PrekeyRecord, Long> IDENTITY_PREKEY = Identities0.IDENTITY_PREKEY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ConversationMessageRecord> CONVERSATION_MESSAGE_PKEY = UniqueKeys0.CONVERSATION_MESSAGE_PKEY;
    public static final UniqueKey<ConversationMessageRecord> CONVERSATION_MESSAGE_CONVERSATION_ID_MESSAGE_INDEX_KEY = UniqueKeys0.CONVERSATION_MESSAGE_CONVERSATION_ID_MESSAGE_INDEX_KEY;
    public static final UniqueKey<CowpiUserRecord> COWPI_USER_PKEY = UniqueKeys0.COWPI_USER_PKEY;
    public static final UniqueKey<CowpiUserRecord> COWPI_USER_USERNAME_KEY = UniqueKeys0.COWPI_USER_USERNAME_KEY;
    public static final UniqueKey<MailboxRecord> MAILBOX_PKEY = UniqueKeys0.MAILBOX_PKEY;
    public static final UniqueKey<OesMessageRecord> OES_MESSAGE_PKEY = UniqueKeys0.OES_MESSAGE_PKEY;
    public static final UniqueKey<OesMessageRecord> OES_MESSAGE_CONVERSATION_MESSAGE_OES_SERVICE_KEY = UniqueKeys0.OES_MESSAGE_CONVERSATION_MESSAGE_OES_SERVICE_KEY;
    public static final UniqueKey<OesPrekeyRecord> OES_PREKEY_PKEY = UniqueKeys0.OES_PREKEY_PKEY;
    public static final UniqueKey<OesPrekeyRecord> OES_PREKEY_OES_ID_KEY_ID_KEY = UniqueKeys0.OES_PREKEY_OES_ID_KEY_ID_KEY;
    public static final UniqueKey<OesPrekeyRecord> OES_PREKEY_PREKEY_KEY = UniqueKeys0.OES_PREKEY_PREKEY_KEY;
    public static final UniqueKey<OesServiceRecord> OES_SERVICE_PKEY = UniqueKeys0.OES_SERVICE_PKEY;
    public static final UniqueKey<OesServiceRecord> OES_SERVICE_OES_NAME_KEY = UniqueKeys0.OES_SERVICE_OES_NAME_KEY;
    public static final UniqueKey<PrekeyRecord> PREKEY_PKEY = UniqueKeys0.PREKEY_PKEY;
    public static final UniqueKey<PrekeyRecord> PREKEY_USER_ID_KEY_ID_KEY = UniqueKeys0.PREKEY_USER_ID_KEY_ID_KEY;
    public static final UniqueKey<PrekeyRecord> PREKEY_PREKEY_KEY = UniqueKeys0.PREKEY_PREKEY_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MailboxRecord, CowpiUserRecord> MAILBOX__MAILBOX_USER_TO_FKEY = ForeignKeys0.MAILBOX__MAILBOX_USER_TO_FKEY;
    public static final ForeignKey<OesMessageRecord, OesServiceRecord> OES_MESSAGE__OES_MESSAGE_OES_SERVICE_FKEY = ForeignKeys0.OES_MESSAGE__OES_MESSAGE_OES_SERVICE_FKEY;
    public static final ForeignKey<OesMessageRecord, ConversationMessageRecord> OES_MESSAGE__OES_MESSAGE_CONVERSATION_MESSAGE_FKEY = ForeignKeys0.OES_MESSAGE__OES_MESSAGE_CONVERSATION_MESSAGE_FKEY;
    public static final ForeignKey<OesPrekeyRecord, OesServiceRecord> OES_PREKEY__OES_PREKEY_OES_ID_FKEY = ForeignKeys0.OES_PREKEY__OES_PREKEY_OES_ID_FKEY;
    public static final ForeignKey<PrekeyRecord, CowpiUserRecord> PREKEY__PREKEY_USER_ID_FKEY = ForeignKeys0.PREKEY__PREKEY_USER_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ConversationMessageRecord, Long> IDENTITY_CONVERSATION_MESSAGE = Internal.createIdentity(ConversationMessage.CONVERSATION_MESSAGE, ConversationMessage.CONVERSATION_MESSAGE.ID);
        public static Identity<CowpiUserRecord, Long> IDENTITY_COWPI_USER = Internal.createIdentity(CowpiUser.COWPI_USER, CowpiUser.COWPI_USER.ID);
        public static Identity<MailboxRecord, Long> IDENTITY_MAILBOX = Internal.createIdentity(Mailbox.MAILBOX, Mailbox.MAILBOX.ID);
        public static Identity<OesMessageRecord, Long> IDENTITY_OES_MESSAGE = Internal.createIdentity(OesMessage.OES_MESSAGE, OesMessage.OES_MESSAGE.ID);
        public static Identity<OesPrekeyRecord, Long> IDENTITY_OES_PREKEY = Internal.createIdentity(OesPrekey.OES_PREKEY, OesPrekey.OES_PREKEY.ID);
        public static Identity<OesServiceRecord, Long> IDENTITY_OES_SERVICE = Internal.createIdentity(OesService.OES_SERVICE, OesService.OES_SERVICE.ID);
        public static Identity<PrekeyRecord, Long> IDENTITY_PREKEY = Internal.createIdentity(Prekey.PREKEY, Prekey.PREKEY.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ConversationMessageRecord> CONVERSATION_MESSAGE_PKEY = Internal.createUniqueKey(ConversationMessage.CONVERSATION_MESSAGE, "conversation_message_pkey", ConversationMessage.CONVERSATION_MESSAGE.ID);
        public static final UniqueKey<ConversationMessageRecord> CONVERSATION_MESSAGE_CONVERSATION_ID_MESSAGE_INDEX_KEY = Internal.createUniqueKey(ConversationMessage.CONVERSATION_MESSAGE, "conversation_message_conversation_id_message_index_key", ConversationMessage.CONVERSATION_MESSAGE.CONVERSATION_ID, ConversationMessage.CONVERSATION_MESSAGE.MESSAGE_INDEX);
        public static final UniqueKey<CowpiUserRecord> COWPI_USER_PKEY = Internal.createUniqueKey(CowpiUser.COWPI_USER, "cowpi_user_pkey", CowpiUser.COWPI_USER.ID);
        public static final UniqueKey<CowpiUserRecord> COWPI_USER_USERNAME_KEY = Internal.createUniqueKey(CowpiUser.COWPI_USER, "cowpi_user_username_key", CowpiUser.COWPI_USER.USERNAME);
        public static final UniqueKey<MailboxRecord> MAILBOX_PKEY = Internal.createUniqueKey(Mailbox.MAILBOX, "mailbox_pkey", Mailbox.MAILBOX.ID);
        public static final UniqueKey<OesMessageRecord> OES_MESSAGE_PKEY = Internal.createUniqueKey(OesMessage.OES_MESSAGE, "oes_message_pkey", OesMessage.OES_MESSAGE.ID);
        public static final UniqueKey<OesMessageRecord> OES_MESSAGE_CONVERSATION_MESSAGE_OES_SERVICE_KEY = Internal.createUniqueKey(OesMessage.OES_MESSAGE, "oes_message_conversation_message_oes_service_key", OesMessage.OES_MESSAGE.CONVERSATION_MESSAGE, OesMessage.OES_MESSAGE.OES_SERVICE);
        public static final UniqueKey<OesPrekeyRecord> OES_PREKEY_PKEY = Internal.createUniqueKey(OesPrekey.OES_PREKEY, "oes_prekey_pkey", OesPrekey.OES_PREKEY.ID);
        public static final UniqueKey<OesPrekeyRecord> OES_PREKEY_OES_ID_KEY_ID_KEY = Internal.createUniqueKey(OesPrekey.OES_PREKEY, "oes_prekey_oes_id_key_id_key", OesPrekey.OES_PREKEY.OES_ID, OesPrekey.OES_PREKEY.KEY_ID);
        public static final UniqueKey<OesPrekeyRecord> OES_PREKEY_PREKEY_KEY = Internal.createUniqueKey(OesPrekey.OES_PREKEY, "oes_prekey_prekey_key", OesPrekey.OES_PREKEY.PREKEY);
        public static final UniqueKey<OesServiceRecord> OES_SERVICE_PKEY = Internal.createUniqueKey(OesService.OES_SERVICE, "oes_service_pkey", OesService.OES_SERVICE.ID);
        public static final UniqueKey<OesServiceRecord> OES_SERVICE_OES_NAME_KEY = Internal.createUniqueKey(OesService.OES_SERVICE, "oes_service_oes_name_key", OesService.OES_SERVICE.OES_NAME);
        public static final UniqueKey<PrekeyRecord> PREKEY_PKEY = Internal.createUniqueKey(Prekey.PREKEY, "prekey_pkey", Prekey.PREKEY.ID);
        public static final UniqueKey<PrekeyRecord> PREKEY_USER_ID_KEY_ID_KEY = Internal.createUniqueKey(Prekey.PREKEY, "prekey_user_id_key_id_key", Prekey.PREKEY.USER_ID, Prekey.PREKEY.KEY_ID);
        public static final UniqueKey<PrekeyRecord> PREKEY_PREKEY_KEY = Internal.createUniqueKey(Prekey.PREKEY, "prekey_prekey_key", Prekey.PREKEY.PREKEY_);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<MailboxRecord, CowpiUserRecord> MAILBOX__MAILBOX_USER_TO_FKEY = Internal.createForeignKey(net.cowpi.server.jooq.Keys.COWPI_USER_PKEY, Mailbox.MAILBOX, "mailbox__mailbox_user_to_fkey", Mailbox.MAILBOX.USER_TO);
        public static final ForeignKey<OesMessageRecord, OesServiceRecord> OES_MESSAGE__OES_MESSAGE_OES_SERVICE_FKEY = Internal.createForeignKey(net.cowpi.server.jooq.Keys.OES_SERVICE_PKEY, OesMessage.OES_MESSAGE, "oes_message__oes_message_oes_service_fkey", OesMessage.OES_MESSAGE.OES_SERVICE);
        public static final ForeignKey<OesMessageRecord, ConversationMessageRecord> OES_MESSAGE__OES_MESSAGE_CONVERSATION_MESSAGE_FKEY = Internal.createForeignKey(net.cowpi.server.jooq.Keys.CONVERSATION_MESSAGE_PKEY, OesMessage.OES_MESSAGE, "oes_message__oes_message_conversation_message_fkey", OesMessage.OES_MESSAGE.CONVERSATION_MESSAGE);
        public static final ForeignKey<OesPrekeyRecord, OesServiceRecord> OES_PREKEY__OES_PREKEY_OES_ID_FKEY = Internal.createForeignKey(net.cowpi.server.jooq.Keys.OES_SERVICE_PKEY, OesPrekey.OES_PREKEY, "oes_prekey__oes_prekey_oes_id_fkey", OesPrekey.OES_PREKEY.OES_ID);
        public static final ForeignKey<PrekeyRecord, CowpiUserRecord> PREKEY__PREKEY_USER_ID_FKEY = Internal.createForeignKey(net.cowpi.server.jooq.Keys.COWPI_USER_PKEY, Prekey.PREKEY, "prekey__prekey_user_id_fkey", Prekey.PREKEY.USER_ID);
    }
}
