/*
 * This file is generated by jOOQ.
 */
package net.cowpi.server.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import net.cowpi.server.jooq.tables.ConversationMessage;
import net.cowpi.server.jooq.tables.CowpiUser;
import net.cowpi.server.jooq.tables.Mailbox;
import net.cowpi.server.jooq.tables.OesMessage;
import net.cowpi.server.jooq.tables.OesPrekey;
import net.cowpi.server.jooq.tables.OesService;
import net.cowpi.server.jooq.tables.Prekey;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Router extends SchemaImpl {

    private static final long serialVersionUID = -1849268311;

    /**
     * The reference instance of <code>router</code>
     */
    public static final Router ROUTER = new Router();

    /**
     * The table <code>router.conversation_message</code>.
     */
    public final ConversationMessage CONVERSATION_MESSAGE = net.cowpi.server.jooq.tables.ConversationMessage.CONVERSATION_MESSAGE;

    /**
     * The table <code>router.cowpi_user</code>.
     */
    public final CowpiUser COWPI_USER = net.cowpi.server.jooq.tables.CowpiUser.COWPI_USER;

    /**
     * The table <code>router.mailbox</code>.
     */
    public final Mailbox MAILBOX = net.cowpi.server.jooq.tables.Mailbox.MAILBOX;

    /**
     * The table <code>router.oes_message</code>.
     */
    public final OesMessage OES_MESSAGE = net.cowpi.server.jooq.tables.OesMessage.OES_MESSAGE;

    /**
     * The table <code>router.oes_prekey</code>.
     */
    public final OesPrekey OES_PREKEY = net.cowpi.server.jooq.tables.OesPrekey.OES_PREKEY;

    /**
     * The table <code>router.oes_service</code>.
     */
    public final OesService OES_SERVICE = net.cowpi.server.jooq.tables.OesService.OES_SERVICE;

    /**
     * The table <code>router.prekey</code>.
     */
    public final Prekey PREKEY = net.cowpi.server.jooq.tables.Prekey.PREKEY;

    /**
     * No further instances allowed
     */
    private Router() {
        super("router", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CONVERSATION_MESSAGE_ID_SEQ,
            Sequences.COWPI_USER_ID_SEQ,
            Sequences.MAILBOX_ID_SEQ,
            Sequences.OES_MESSAGE_ID_SEQ,
            Sequences.OES_PREKEY_ID_SEQ,
            Sequences.OES_SERVICE_ID_SEQ,
            Sequences.PREKEY_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ConversationMessage.CONVERSATION_MESSAGE,
            CowpiUser.COWPI_USER,
            Mailbox.MAILBOX,
            OesMessage.OES_MESSAGE,
            OesPrekey.OES_PREKEY,
            OesService.OES_SERVICE,
            Prekey.PREKEY);
    }
}
