/*
 * This file is generated by jOOQ.
 */
package net.cowpi.server.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in router
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>router.conversation_message_id_seq</code>
     */
    public static final Sequence<Long> CONVERSATION_MESSAGE_ID_SEQ = new SequenceImpl<Long>("conversation_message_id_seq", Router.ROUTER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>router.cowpi_user_id_seq</code>
     */
    public static final Sequence<Long> COWPI_USER_ID_SEQ = new SequenceImpl<Long>("cowpi_user_id_seq", Router.ROUTER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>router.mailbox_id_seq</code>
     */
    public static final Sequence<Long> MAILBOX_ID_SEQ = new SequenceImpl<Long>("mailbox_id_seq", Router.ROUTER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>router.oes_message_id_seq</code>
     */
    public static final Sequence<Long> OES_MESSAGE_ID_SEQ = new SequenceImpl<Long>("oes_message_id_seq", Router.ROUTER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>router.oes_prekey_id_seq</code>
     */
    public static final Sequence<Long> OES_PREKEY_ID_SEQ = new SequenceImpl<Long>("oes_prekey_id_seq", Router.ROUTER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>router.oes_service_id_seq</code>
     */
    public static final Sequence<Long> OES_SERVICE_ID_SEQ = new SequenceImpl<Long>("oes_service_id_seq", Router.ROUTER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>router.prekey_id_seq</code>
     */
    public static final Sequence<Long> PREKEY_ID_SEQ = new SequenceImpl<Long>("prekey_id_seq", Router.ROUTER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
