/*
 * This file is generated by jOOQ.
 */
package net.cowpi.server.jooq;


import javax.annotation.Generated;

import net.cowpi.server.jooq.tables.ConversationMessage;
import net.cowpi.server.jooq.tables.CowpiUser;
import net.cowpi.server.jooq.tables.Mailbox;
import net.cowpi.server.jooq.tables.OesMessage;
import net.cowpi.server.jooq.tables.OesPrekey;
import net.cowpi.server.jooq.tables.OesService;
import net.cowpi.server.jooq.tables.Prekey;


/**
 * Convenience access to all tables in router
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>router.conversation_message</code>.
     */
    public static final ConversationMessage CONVERSATION_MESSAGE = net.cowpi.server.jooq.tables.ConversationMessage.CONVERSATION_MESSAGE;

    /**
     * The table <code>router.cowpi_user</code>.
     */
    public static final CowpiUser COWPI_USER = net.cowpi.server.jooq.tables.CowpiUser.COWPI_USER;

    /**
     * The table <code>router.mailbox</code>.
     */
    public static final Mailbox MAILBOX = net.cowpi.server.jooq.tables.Mailbox.MAILBOX;

    /**
     * The table <code>router.oes_message</code>.
     */
    public static final OesMessage OES_MESSAGE = net.cowpi.server.jooq.tables.OesMessage.OES_MESSAGE;

    /**
     * The table <code>router.oes_prekey</code>.
     */
    public static final OesPrekey OES_PREKEY = net.cowpi.server.jooq.tables.OesPrekey.OES_PREKEY;

    /**
     * The table <code>router.oes_service</code>.
     */
    public static final OesService OES_SERVICE = net.cowpi.server.jooq.tables.OesService.OES_SERVICE;

    /**
     * The table <code>router.prekey</code>.
     */
    public static final Prekey PREKEY = net.cowpi.server.jooq.tables.Prekey.PREKEY;
}
