/*
 * This file is generated by jOOQ.
 */
package net.cowpi.server.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import net.cowpi.server.jooq.Indexes;
import net.cowpi.server.jooq.Keys;
import net.cowpi.server.jooq.Router;
import net.cowpi.server.jooq.tables.records.OesPrekeyRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OesPrekey extends TableImpl<OesPrekeyRecord> {

    private static final long serialVersionUID = -625990176;

    /**
     * The reference instance of <code>router.oes_prekey</code>
     */
    public static final OesPrekey OES_PREKEY = new OesPrekey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OesPrekeyRecord> getRecordType() {
        return OesPrekeyRecord.class;
    }

    /**
     * The column <code>router.oes_prekey.id</code>.
     */
    public final TableField<OesPrekeyRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('router.oes_prekey_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>router.oes_prekey.oes_id</code>.
     */
    public final TableField<OesPrekeyRecord, Long> OES_ID = createField("oes_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>router.oes_prekey.key_id</code>.
     */
    public final TableField<OesPrekeyRecord, Long> KEY_ID = createField("key_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>router.oes_prekey.prekey</code>.
     */
    public final TableField<OesPrekeyRecord, byte[]> PREKEY = createField("prekey", org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

    /**
     * Create a <code>router.oes_prekey</code> table reference
     */
    public OesPrekey() {
        this(DSL.name("oes_prekey"), null);
    }

    /**
     * Create an aliased <code>router.oes_prekey</code> table reference
     */
    public OesPrekey(String alias) {
        this(DSL.name(alias), OES_PREKEY);
    }

    /**
     * Create an aliased <code>router.oes_prekey</code> table reference
     */
    public OesPrekey(Name alias) {
        this(alias, OES_PREKEY);
    }

    private OesPrekey(Name alias, Table<OesPrekeyRecord> aliased) {
        this(alias, aliased, null);
    }

    private OesPrekey(Name alias, Table<OesPrekeyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OesPrekey(Table<O> child, ForeignKey<O, OesPrekeyRecord> key) {
        super(child, key, OES_PREKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Router.ROUTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OES_PREKEY_OES_ID_KEY_ID_KEY, Indexes.OES_PREKEY_PKEY, Indexes.OES_PREKEY_PREKEY_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OesPrekeyRecord, Long> getIdentity() {
        return Keys.IDENTITY_OES_PREKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OesPrekeyRecord> getPrimaryKey() {
        return Keys.OES_PREKEY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OesPrekeyRecord>> getKeys() {
        return Arrays.<UniqueKey<OesPrekeyRecord>>asList(Keys.OES_PREKEY_PKEY, Keys.OES_PREKEY_OES_ID_KEY_ID_KEY, Keys.OES_PREKEY_PREKEY_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OesPrekeyRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OesPrekeyRecord, ?>>asList(Keys.OES_PREKEY__OES_PREKEY_OES_ID_FKEY);
    }

    public OesService oesService() {
        return new OesService(this, Keys.OES_PREKEY__OES_PREKEY_OES_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OesPrekey as(String alias) {
        return new OesPrekey(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OesPrekey as(Name alias) {
        return new OesPrekey(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OesPrekey rename(String name) {
        return new OesPrekey(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OesPrekey rename(Name name) {
        return new OesPrekey(name, null);
    }
}
